### ISSUE TITLE
📃: Turtle Graphics

### ISSUE THREAD

**Issue by yashi-025** [UTSAVS26/PyVerse#10]
:red_circle: **Title** : Turtle Graphics
:red_circle: **Aim** :  Python Turtle graphics examples for Beginner_Projects section
:red_circle: **Brief Explanation** : Turtle is a Python standard library that provides a simple way to create drawings and graphics using a virtual "turtle" that moves around the screen based on commands.
Example:
1. Drawing shapes (e.g., squares, circles, triangles, spiral)
2. Creating simple animations

### Screenshots 📷

![Screenshot 2024-10-01 200932](https://github.com/user-attachments/assets/441c5561-6e1d-4ec5-ad79-1cb64c02be26)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Yashika Garg
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)  
      Contributor for WoB'24

***********************************************************************
Please add labels and assign this issue to me. @yashi-025

**Comment by UTSAVS26** [comment]
@yashi-025 you can start working on it

**Comment by yashi-025** [comment]
Thanks Utsav for giving me this opportunity.

**Comment by UTSAVS26** [comment]
> Thanks Utsav for giving me this opportunity.

You are welcome
