### ISSUE TITLE
[Code Addition Request]:  Want to Add a web application for image compression & filter tools in image processing folder

### ISSUE THREAD

**Issue by Jivanjamadar** [UTSAVS26/PyVerse#1012]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/847#event-14885412454

### Project Description

The Image Resizer and Filter Tool is a **web-based application** that allows users to upload images, resize them, apply various filters, and download the processed images. Built with HTML, CSS, and JavaScript, this tool provides an intuitive interface for manipulating images directly in the browser.

**Features :**

- **Image Upload:** Easily upload images from your device.
- **Resize Functionality:** Adjust the size of the image using a percentage slider.
- **Filters:** Apply various filters such as brightness, contrast, saturation, and blur.
- **Preview**: View real-time changes on the canvas.
- **Download:** Save the processed image to your device.

This project demonstrates the power of client-side JavaScript in handling complex tasks like image processing while providing a seamless user experience. With a clean and intuitive layout, the tool is practical for both casual users and developers needing quick image adjustments on the fly. Also with interactive UI and better UX, user can easily do the task.

### Full Name

Jivan Jamdar

### Participant Role

GSSOC

**Comment by Jivanjamadar** [comment]
@UTSAVS26  assign this issue to me.

**Comment by UTSAVS26** [comment]
@Jivanjamadar do you plan to use Python in it?

**Comment by Jivanjamadar** [comment]
@UTSAVS26  No, using JS for functionality

**Comment by UTSAVS26** [comment]
> @UTSAVS26  No. For functionality using JS only as of now. But as pyverse repo focuses on only python so I will add some more features in web app.
> 

Okie

**Comment by UTSAVS26** [comment]
But if I don't python integrated I will close the PR.

**Comment by Jivanjamadar** [comment]
@UTSAVS26  Can you change the level to level 2. Cause it's a good project where the frontend and backend working with integration.

**Comment by UTSAVS26** [comment]
> @UTSAVS26  Can you change the level to level 2. Cause it's a good project where the frontend and backend working with integration.
> 

Not possible as you are adding the project and it is counted under level1.
