### ISSUE TITLE
[Code Addition Request]:  Add a Grammar Autocorrector Model

### ISSUE THREAD

**Issue by Peart-Guy** [UTSAVS26/PyVerse#1027]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/858

### Project Description

I want to add a Grammar AutoCorrector NLP model

### Full Name

Ankan

### Participant Role

GSSOC-24 EXTD

**Comment by Peart-Guy** [comment]
@UTSAVS26  KIndly assign me this issue and tell me highest level i can get upon adding the model

**Comment by UTSAVS26** [comment]
> @UTSAVS26  KIndly assign me this issue and tell me highest level i can get upon adding the model 

Only level1 as you are adding project.
