### ISSUE TITLE
📃: Addition in Automation Tools

### ISSUE THREAD

**Issue by Himanshi-m** [UTSAVS26/PyVerse#103]
:red_circle: **Title** : Addition of an Image tool in Automation tools section
:red_circle: **Aim** : To add a project of image resizer and converter in tools section
:red_circle: **Brief Explanation** : A tool that Automatically resizes or converts a batch of images applying uniform dimensions or format conversion (e.g., PNG to JPEG).

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: 
- Full name : Himanshi Maheshwari
- What is your participant role? gssoc-extd contributor and hacktoberfest

***********************************************************************

**Comment by Himanshi-m** [comment]
Thank you I'm working on it. Also, i think the label of Hacktoberfest should be hacktoberfest-accepted as per guidelines... Please take a look at the same.

**Comment by UTSAVS26** [comment]
> Thank you I'm working on it. Also, i think the label of Hacktoberfest should be hacktoberfest-accepted as per guidelines... Please take a look at the same. 

**`hacktoberfest-accepted` should be added to the merged PR and only `hacktoberfest` label to issues.** Thats what me and mentors have decided to maintain proper structure.

**Comment by Himanshi-m** [comment]
Alright.
