### ISSUE TITLE
[Code Addition Request]: Add Levenshtein Distance Algo

### ISSUE THREAD

**Issue by NK-Works** [UTSAVS26/PyVerse#1040]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#1039

### Project Description

Add levenshtein algo

### Full Name

Anneshu Nag

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@NK-Works little advice from my side, don't do these things like adding one code per issue to just gain points on leaderboard. If you want to contribute properly then raise a proper issue adding all the algorithms you are planning to add.
