### ISSUE TITLE
[Code Addition Request]: IoT Device Control Script

### ISSUE THREAD

**Issue by dino65-dev** [UTSAVS26/PyVerse#1042]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/780

## IoT Device Control Script
This Python script is designed to facilitate secure and efficient communication with IoT devices using the MQTT protocol. It leverages the paho-mqtt library to connect to an MQTT broker, publish commands, and handle responses from IoT devices. The script is enhanced with several advanced features to ensure robust and secure operations:
1.Secure Communication: Utilizes TLS/SSL to encrypt data transmitted between the client and the MQTT broker, ensuring that all communications are secure and protected against eavesdropping.
2.Dynamic Topic Management: Allows for flexible management of MQTT topics, enabling the script to subscribe to and publish messages on various topics as needed.
3.Enhanced Error Handling: Implements comprehensive error handling mechanisms to manage connection issues and message delivery failures, ensuring reliability and stability in various network conditions.
4.Logging: Incorporates detailed logging using Python's logging module, providing insights into the script's operations and facilitating troubleshooting and monitoring.

### Full Name

Dinmay Kumar Brahma

### Participant Role

- ### GSSOC-EXT 2024
- ### CONTRIBUTOR

**Comment by UTSAVS26** [comment]
@dino65-dev what tech stack you are planning to use?

**Comment by dino65-dev** [comment]
Programming Language: Python 
Communication Protocol: MQTT [ MQTT Library: Paho-MQTT  ]
Security: TLS/SSL
Logging: Python's logging module

**Comment by UTSAVS26** [comment]
@dino65-dev try to list the iot devices it can work on easily or add few example too of different iot based projects that can utilise this.

**Comment by dino65-dev** [comment]
@UTSAVS26 Sure.
