### ISSUE TITLE
[Code Addition Request]: Histogram Maximal Rectangle DP Hard

### ISSUE THREAD

**Issue by NK-Works** [UTSAVS26/PyVerse#1061]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#1040

### Project Description

Add maximal rectangle in histogram

### Full Name

Anneshu Nag

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@NK-Works I am closing this issue, raise another issue add add atleast 3-4 slogs not just 1.

**Comment by NK-Works** [comment]
@UTSAVS26 got it
