### ISSUE TITLE
📃: API development for book store management

### ISSUE THREAD

**Issue by ojhankit** [UTSAVS26/PyVerse#108]
:red_circle: **Title** : 
Bookstore API 
:red_circle: **Aim** : 
To create an API for bookstore with CRUD functionality with use of in memory databases
:red_circle: **Brief Explanation** : 
Using FastAPI I'll create API for book store management which includes CRUD operation 
1.Create :- admin can add new books
2.Read   :- admin can view books which are present in the store
3.Update:- admin can update details of existing books
4.delete :- admin can remove any book 
### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ankit Ojha 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
contributor gssoc-ext
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ojhankit** [comment]
@UTSAVS26  could you check this.. and also i can use mysql for databases.

**Comment by UTSAVS26** [comment]
> @UTSAVS26  could you please check this.. and also i can use mysql for databases.

Yes you can use but you need to provide a detailed instructions too for the project how one can use it, if that person is not a technical.

**Comment by ojhankit** [comment]
okayy thanks
