### ISSUE TITLE
[Code Addition Request]: Goofy Quiz Game

### ISSUE THREAD

**Issue by priyashuu** [UTSAVS26/PyVerse#1086]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/1081

### Project Description

Game Title: Goof Typing Challenge

Description
The Goof Typing Challenge is a fast-paced typing game designed to test your speed and accuracy under pressure. In this game, random words are displayed one by one, and your goal is to type each word correctly within a limited time. The faster you type, the higher your score, but beware—one mistake or a delayed response ends the game instantly!

This game combines elements of quick thinking, typing skills, and a dash of humor, as the game can unexpectedly surprise you with a few quirky, tech-related words. It’s perfect for anyone looking to improve their typing speed while having some goofy fun!

### Full Name

Priya Rani

### Participant Role

ggsoc,wboc

**Comment by UTSAVS26** [comment]
@priyashuu https://github.com/UTSAVS26/PyVerse/issues/1073
