### ISSUE TITLE
[Code Addition Request]: Middle of Linked List

### ISSUE THREAD

**Issue by SKG24** [UTSAVS26/PyVerse#1087]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/1079#event-15113087781

### Project Description

Given the head of a singly linked list, return the middle node of the linked list.
If there are two middle nodes, return the second middle node.
Input: head = [1,2,3,4,5]
Output: [3,4,5]
Explanation: The middle node of the list is node 3.

Idea is to use two pointer fast and slow to find the middle node

### Full Name

Sanat Kumar Gupta

### Participant Role

gssoc-ext

**Comment by UTSAVS26** [comment]
@SKG24 https://github.com/UTSAVS26/PyVerse/issues/1073
