### ISSUE TITLE
🧑‍💻: Enhance Crossword Puzzle Game: Add Difficulty Levels, Timer, Scoring, Leaderboard, and UI Customizations

### ISSUE THREAD

**Issue by Kritika75** [UTSAVS26/PyVerse#1089]
### Title

Enhance Crossword Puzzle Game: Add Difficulty Levels, Timer, Scoring, Leaderboard, and UI Customizations

my latest merged PR link: https://github.com/UTSAVS26/PyVerse/pull/1064

### Enhancement Aim

The enhancement aims to elevate the Crossword Puzzle Game by introducing difficulty levels (Easy, Medium, Hard) for varied challenges, along with a timer and scoring system to reward quick completions. A leaderboard will track high scores, while progress tracking allows players to save their levels. UI improvements, including theme customization and dynamic letter placement, will enhance visual appeal. Lastly, random word generation will ensure a unique experience with shuffled letters for each attempt. These features will make the game more engaging and user-friendly for a broader audience.

### Changes

1. Difficulty Levels: Add Easy, Medium, and Hard levels, with variations in word length and complexity.
2. Timer and Scoring: Implement a countdown timer and scoring system, rewarding faster completions with higher scores.
3. Leaderboard: Track high scores, allowing players to view and compete.
4. Progress Tracking: Save level progress to let players resume where they left off.
5. UI and Theme Customization: Add light and dark mode themes and improve grid visuals with dynamic letter placement.
6. Random Word Generation: Ensure unique word choices with shuffled letters on each attempt.

### Screenshots 📷

N/a

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Kritika Singh

### Participant Role

GSSOC'24 ext

@UTSAVS26 can you assign me this??

**Comment by UTSAVS26** [comment]
@Kritika75 https://github.com/UTSAVS26/PyVerse/issues/1073
