### ISSUE TITLE
[Code Addition Request]: Bit plane slicing using OPEN CV & Matplot Lib

### ISSUE THREAD

**Issue by Suvadip-sana** [UTSAVS26/PyVerse#1092]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#990 

### Project Description

Bit plane slicing using opencv and matplotlib. It's slice the image of it's 8 bit lsb
![image](https://github.com/user-attachments/assets/c6dcd67f-c7e2-47db-b190-7a8582d63eb0)

### Full Name

Suvadip Sana

### Participant Role

`gssoc-ext`, `hacktoberfest`

**Comment by UTSAVS26** [comment]
@Suvadip-sana https://github.com/UTSAVS26/PyVerse/issues/1073
