### ISSUE TITLE
[Code Addition Request]: String Reversal using Stack

### ISSUE THREAD

**Issue by shuvojitss** [UTSAVS26/PyVerse#1096]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#1077

### Name:  
```[NEW ALGORITHM]```  Write a program to reverse a string using stack data structure.

### About:  
Implementation of stack data structure.
### Input:
A single string of up to 100 characters, which may contain spaces and other characters.
### Output:
The reversed string.
### Time Complexity: 
O(n), where n is the length of the string. This is because each character is pushed and popped from the stack exactly once.
### Space complexity: 
O(n), where n is the length of the string, since the stack needs to store the characters temporarily.

### Full Name

Shuvojit Samanta

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@shuvojitss https://github.com/UTSAVS26/PyVerse/issues/1073
