### ISSUE TITLE
[Code Addition Request]: Addition of Color Mixer Challenge Game

### ISSUE THREAD

**Issue by pratheekv39** [UTSAVS26/PyVerse#1106]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/1072

### Project Description

The Color Mixer Challenge is a Python-based game that allows players to experiment with RGB color values. The goal of the game is to mix primary colors (Red, Green, and Blue) to match a randomly generated target color as closely as possible. This game tests your understanding of color theory and can be a fun way to learn about how RGB values combine to create different colors.

### Full Name

V Pratheek

### Participant Role

Contributor at GSSOC and Hacktoberfest

**Comment by UTSAVS26** [comment]
@pratheekv39 please read #1073
