### ISSUE TITLE
[Code Addition Request]: Add Box Stacking Problem, Arithmetic Slices, Word Ladder II (Shortest Transformation Sequence)

### ISSUE THREAD

**Issue by NK-Works** [UTSAVS26/PyVerse#1107]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#1094 

### Project Description

Add algos: 
Box Stacking Problem
Arithmetic Slices
Word Ladder II (Shortest Transformation Sequence)

### Full Name

Anneshu Nag

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@NK-Works please read this #1073

**Comment by NK-Works** [comment]
@UTSAVS26 bro read it now :)
kinda understand its one of the most active repos of the entire GSSOC
its been great to contribute to this repo....
PEACE OUT! ✌️
