### ISSUE TITLE
📃: Add project "Autofill Personal Info Using Adhaar Card Image" under automation category.

### ISSUE THREAD

**Issue by Mayank202004** [UTSAVS26/PyVerse#111]
:red_circle: **Title** : Autofill Personal Info Using Adhaar Card
:red_circle: **Aim** : To reduce manual work of typing personal details while applying for any online application that requires adhaar card ex. scholarships etc.
:red_circle: **Brief Explanation** : The system will use machine learning OCR to convert the adhaar card image to text and then with the use of Regular Expressions fetch necessary information like first name last name etc.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Mayank Sachin Chougale
- What is your participant role? GSSOC EXT

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SatyaD012** [comment]
@UTSAVS26 Hello,
I'd like to work on this issue. Please assign it to me.

**Comment by UTSAVS26** [comment]
@Mayank202004 work on 1 issue at a time, i am assigning this issue to @SatyaD012

**Comment by UTSAVS26** [comment]
@SatyaD012 please tell your participation role.

**Comment by Mayank202004** [comment]
Assign me
