### ISSUE TITLE
adding Reverse array using Two Pointer technique

### ISSUE THREAD

**Issue by avinashkrsingh01** [UTSAVS26/PyVerse#1113]
### Issue Summary

In array folder I want to add Reverse array using Two Pointer technique

### Issue Description

 Reverse array using Two Pointer technique

### Proposed Solution (Optional)

 using Two Pointer technique

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

**Comment by avinashkrsingh01** [comment]
@UTSAVS26 "I would love the opportunity to contribute and work on this project.
Could you please assign the issue to me? I'm eager to dive in and make a meaningful impact. Thank you for considering my request!"

**Comment by UTSAVS26** [comment]
@avinashkrsingh01 please read this once #1073.
