### ISSUE TITLE
[Code Addition Request]: predict the Site EUI usin Explainable AI

### ISSUE THREAD

**Issue by inkerton** [UTSAVS26/PyVerse#1115]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#1109 

### Project Description

prediction task involving roughly 100k observations of building energy usage records collected over 7 years and a number of states within the United States. The dataset consists of building characteristics (e.g. floor area, facility type etc), weather data for the location of the building (e.g. annual average temperature, annual total precipitation etc) as well as the energy usage for the building and the given year, measured as Site Energy Usage Intensity (Site EUI). Each row in the data corresponds to the a single building observed in a given year. Your task is to predict the Site EUI for each row, given the characteristics of the building and the weather data for the location of the building.

### Full Name

inkerton

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@inkerton read this first #1073.
