### ISSUE TITLE
[Code Addition Request]: Adding String matching algorithm

### ISSUE THREAD

**Issue by Anushkam09** [UTSAVS26/PyVerse#1118]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

I would like to add string matching algorithm: boyer moore algorithm, kmp agorithm

### Full Name

Anushka Mahajan

### Participant Role

GSSOC Extended 2024 Contributor

**Comment by UTSAVS26** [comment]
Please read this #1073.
