### ISSUE TITLE
[Code Addition Request]: City Moodscape: Visualizing City Moods through Social Media Sentiment and Weather Data

### ISSUE THREAD

**Issue by Ananya-vastare** [UTSAVS26/PyVerse#1119]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/1101

### Project Description

Create an interactive, multi-layered visualization that displays the "mood" of different cities over time by analyzing social media sentiment (like tweets) and combining it with weather data. This project would involve gathering and processing real-time or historical data on social sentiment and weather patterns, then representing the "city mood" through colors, shapes, or other creative visual elements.

### Full Name

Ananya Ravikiran Vastare

### Participant Role

GSSOC - extd

**Comment by Ananya-vastare** [comment]
@UTSAVS26 please assign this issue to me

**Comment by UTSAVS26** [comment]
@Ananya-vastare please read this #1073.
