### ISSUE TITLE
📃: "IRIS DATASET CLASSIFICATION USING KNN" under machine learning/k-nearest-neighbors/

### ISSUE THREAD

**Issue by Mayank202004** [UTSAVS26/PyVerse#112]
:red_circle: **Title** : IRIS DATASET CLASSIFICATION USING KNN
:red_circle: **Aim** : The aim of this project is to help beginners learn how KNN algorithm works
:red_circle: **Brief Explanation** : 
- This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray
- The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length and Petal Width.
- The project aims to classify these irises types using KNN algorithm

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mayank Sachin Chougale
- What is your participant role? GSSOC EXT

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by UTSAVS26** [comment]
> Can you please assign it to me? I want to work on it.

I have already assigned this issue to @Mayank202004, you can raise new issue and work on that.
