### ISSUE TITLE
🧑‍💻: [Modify / Add Code] KBC Quiz

### ISSUE THREAD

**Issue by saanvi23454** [UTSAVS26/PyVerse#1122]
### Title

Align display for better clarity in KBC Quiz

### Enhancement Aim

to enhance display and functionality

### Changes

Fix the * and - to have the same alignment from right and left, 
and print the correct answer once the quiz is over due to wrong answer or quiting.

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Saanvi Singh

### Participant Role

GSSOC contributor

**Comment by UTSAVS26** [comment]
@saanvi23454 sorry but we are not accepting new issues and PRs, you can check #1073. We are accepting only those ORs that have assigned issues before.
