### ISSUE TITLE
[Code Addition Request]: Want to add priority search algorithm in searching algorithm folder

### ISSUE THREAD

**Issue by Jivanjamadar** [UTSAVS26/PyVerse#1123]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/1029

### Project Description

Priority Search is a type of search algorithm that efficiently handles searching in a set of intervals. It's commonly used for searching in interval trees, where each item in the dataset has a range (start, end), and we want to quickly find which intervals contain a given point.

### Full Name

Jivan Jamdar

### Participant Role

GSSOC

**Comment by Jivanjamadar** [comment]
@UTSAVS26 assign this issue to me

**Comment by UTSAVS26** [comment]
@Jivanjamadar go through this #1073
