### ISSUE TITLE
[Custom]: Will this repo open for SWOC

### ISSUE THREAD

**Issue by abhirajadhikary06** [UTSAVS26/PyVerse#1134]
### Issue Summary

I had a query if this repo is actively participating in SWOC

### Issue Description

If this repo is participating in SWOC I would like to contribute to this repo with some advance projects of Python.

### Priority

High - Requires urgent attention

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

**Comment by UTSAVS26** [comment]
@abhirajadhikary06 the repo is participating in SWOC. You can start contribution from 1st of Jan as per the timeline.
