### ISSUE TITLE
📃: Landmark Detection Web Application

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PyVerse#114]
:red_circle: **Title** : Landmark Detect Web App
:red_circle: **Aim** : To create a simple yet interactive web application using streamlit or flask framework, that can predict the landmark using open-source models
:red_circle: **Brief Explanation** : The main is to show the advance tools & techniques in the Machine Learning & Data science development.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Yash K. Saini
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

**GSSOC** contributor

***********************************************************************

@UTSAVS26 can you assign this issue to me & add labels.

**Comment by yashksaini-coder** [comment]
this issue could be `level 3`

**Comment by yashksaini-coder** [comment]
@UTSAVS26 This can also be `level 3` don't U think

**Comment by UTSAVS26** [comment]
Based on the work i will update the level.
