### ISSUE TITLE
📃: Real time translation ML project

### ISSUE THREAD

**Issue by 770navyasharma** [UTSAVS26/PyVerse#118]
🚀 It is a very great resource. To make it even more powerful, I'd love to contribute by adding a real-time translation model under Machine Learning covering more than 10 languages—focusing especially on Indian regional languages. This feature will include both speech-to-text and text-to-speech integrations, all wrapped in an interactive Streamlit app for seamless user experience.

What will this feature add?
🔄 Real-Time Translation across multiple languages.
🎤 Speech-to-Text: Users can speak in their native language, and the model will transcribe the audio in real-time.
🗣️ Text-to-Speech: The translated text can also be played back in the target language.
🌐 Focus on Indian regional languages to cater to a diverse audience.
🎛️ User-Friendly Interface using Streamlit for smooth interaction and accessibility.

💡 I’m excited to work on this! Kindly assign me this task under the following tags:

hacktoberfest 🎉
gssoc-extd 👩‍💻
level 2 or 3 📈
Looking forward to contributing and taking this repository to the next level! 💪

cc: @UTSAVS26

**Comment by UTSAVS26** [comment]
@770navyasharma based on the work i can increase the level of it.
