### ISSUE TITLE
📃: Face Recognition System

### ISSUE THREAD

**Issue by anirudh-248** [UTSAVS26/PyVerse#119]
:red_circle: **Face Recognition System** :
:red_circle: **The Facial Recognition System project aims to develop a real-time application that detects and recognizes faces using YOLO for face detection and the face_recognition library for embedding extraction, enabling automated identification in security and access control scenarios.** :
:red_circle: **The Facial Recognition System is designed to detect and recognize faces in real-time using a combination of the Ultralytics YOLO model, the face_recognition library, and OpenCV for live video processing. The system utilizes supervised learning by training on a labeled dataset of known faces, where each face is associated with an identity. The project creates a pipeline that detects faces from a live video feed, extracts facial features, and matches them against the labeled dataset for identification. The system effectively classifies faces based on learned features by using YOLO for object detection and face_recognition for embedding extraction and comparison. This project is ideal for real-time surveillance, security, and access control applications.** :

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue:**
- Full name : Anirudh P S
- What is your participant role? GSSoC Extd

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
> @UTSAVS26 in what domain should i add this project?

In deep learning
