### ISSUE TITLE
📃: A Chatbot which guides user according to need

### ISSUE THREAD

**Issue by Peart-Guy** [UTSAVS26/PyVerse#120]
:red_circle: **Title** : AI Chatbot 
:red_circle: **Aim** : To provide programmers a chatbot which  they can attach it with their wesite and train them to their need.
:red_circle: **Brief Explanation** :This chatbot will help users by helping them in any related problems. The chatbot will have a feature of Natural Language which will easily omit user's grammatical mistakes and spelling mistakes in chat input. The admin can train the chatbot whenever needed in a .json file.

-->The chatbot will have its back end in Python with modules like PyTorch, NumPy, etc. and and a basic front end in CSS and JS and HTML

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ankan
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) : GSSOC-24 Extd

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Peart-Guy** [comment]
@UTSAVS26  
This git clone issue is coming ... KIndly Look into this matter
![WhatsApp Image 2024-10-05 at 20 56 19_0500ad14](https://github.com/user-attachments/assets/0abe5dd5-8892-4bc6-a420-f30888bec624)

**Comment by UTSAVS26** [comment]
Try tomorrow as i have revert back one PR which has some faults including naming of the file that's why the error is coming .

**Comment by Peart-Guy** [comment]
I have done the work. Kindly check it out

**Comment by devkartikrathi** [comment]
@UTSAVS26 I would like to contribute to this repository and I also want to suggest a separate folder for NLP projects because we have a very large scope for AI agents and chat bots. I am an NLP Engineer and currently doing my research in LLM Fine-tuning.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 I would like to contribute to this repository and I also want to suggest a separate folder for NLP projects because we have a very large scope for AI agents and chat bots. I am an NLP Engineer and currently doing my research in LLM Fine-tuning.

Sorry @devkartikrathi the PR for this issue has been merged and my mistake this issue is still open. Sort for the trouble and you can raise a new issue.
