### ISSUE TITLE
🧑‍💻: add pattern search algorithm

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [UTSAVS26/PyVerse#127]
:red_circle: **Title** : pattern search algorithm
:red_circle: **Enhancement Aim** :add pattern search algorithm
:red_circle: **Changes** : 
pattern search algorithm to the file 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Chiluka Akshitha
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) gssoc and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by AKSHITHA-CHILUKA** [comment]
I have complete it and about to merge it
