### ISSUE TITLE
📃: Binary Tree

### ISSUE THREAD

**Issue by Anushkam09** [UTSAVS26/PyVerse#13]
:red_circle: **Title** : Binary Tree
:red_circle: **Aim** : Binary Tree DSA
:red_circle: **Brief Explanation** : Showing all the basic operations on Binary Tree using a menu-driven program.

### Screenshots 📷 
 
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anushka Mahajan
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC 24' Extended Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Pavitra-s-Workspace** [comment]
Uppada Pavitra Manaswini Reddy
GSSoC24' Extended Contributor
Im interested to contribute please assign me.

**Comment by UTSAVS26** [comment]
> Uppada Pavitra Manaswini Reddy
> GSSoC24' Extended Contributor
> Im interested to contribute please assign me.

Hi @Pavitra-s-Workspace you can raise another issue , I will assign that issue to you. All the best

**Comment by Pavitra-s-Workspace** [comment]
> > Uppada Pavitra Manaswini Reddy
> > GSSoC24' Extended Contributor
> > Im interested to contribute please assign me.
> 
> Hi @Pavitra-s-Workspace you can raise another issue , I will assign that issue to you. All the best

ok, Thank you.
