### ISSUE TITLE
📃:  Adding Bfs and dfs in data structure and algorithms 

### ISSUE THREAD

**Issue by Charul00** [UTSAVS26/PyVerse#132]
:red_circle: **Title** :  
Add BFS and DFS Algorithm Implementations

:red_circle: **Aim** :  
To implement Breadth-First Search (BFS) and Depth-First Search (DFS) algorithms for traversing or searching tree or graph data structures.

:red_circle: **Brief Explanation** :  
This contribution aims to add the implementations of BFS and DFS algorithms, which are fundamental techniques for exploring and searching tree and graph structures. BFS explores all the vertices at the present depth level before moving on to the vertices at the next depth level, while DFS explores as far as possible along each branch before backing up. The implementation will include both iterative and recursive approaches for each algorithm and will provide example use cases to demonstrate their functionality.

### Screenshots 📷
  
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Charul Chim
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)  
GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Charul00** [comment]
@UTSAVS26 please add the gssoc-ext and level

**Comment by UTSAVS26** [comment]
@Charul00 this issue has already been done https://github.com/UTSAVS26/PyVerse/tree/main/Algorithms_and_Data_Structures%2FDesign_and_Analysis_of_Algorithms%2FGraph_Traversing you can check here.

**Comment by UTSAVS26** [comment]
@Charul00 this issue has already been done https://github.com/UTSAVS26/PyVerse/tree/main/Algorithms_and_Data_Structures%2FDesign_and_Analysis_of_Algorithms%2FGraph_Traversing you can check here.
