### ISSUE TITLE
📃: Adding Web Development resources

### ISSUE THREAD

**Issue by Charul00** [UTSAVS26/PyVerse#134]
:red_circle: **Title** :  
Add Web Development Resources

:red_circle: **Aim** :  
To compile a list of useful web development resources, including tutorials, documentation, and PDFs for beginners and professionals.

:red_circle: **Brief Explanation** :  
This contribution aims to gather a collection of web development resources, focusing on different aspects like frontend, backend, full-stack development, and responsive design. The resources will include tutorials, documentation, ebooks, and articles that cover popular technologies such as HTML, CSS, JavaScript, React, Node.js, and more. Each resource will be briefly described for ease of access and understanding.

### Web Development Resources 📚

1. **[HTML & CSS: Design and Build Websites](https://example.com/html-css-book.pdf)**  
   A beginner-friendly guide to HTML and CSS, covering the basics of web design and development.

2. **[JavaScript: The Good Parts](https://example.com/javascript-good-parts.pdf)**  
   A must-read for JavaScript developers that covers the language's most powerful features and good practices.

3. **[React Documentation](https://reactjs.org/docs/getting-started.html)**  
   Official documentation for React, one of the most popular JavaScript libraries for building user interfaces.

4. **[Node.js in Action](https://example.com/nodejs-in-action.pdf)**  
   A comprehensive guide to building scalable web applications with Node.js, Express, and other related technologies.

5. **[Responsive Web Design with HTML5 and CSS3](https://example.com/responsive-web-design.pdf)**  
   A resource for learning how to create responsive and mobile-friendly websites using modern HTML5 and CSS3 techniques.

6. **[Full Stack Web Development with React and Node.js](https://example.com/fullstack-development.pdf)**  
   This resource covers full-stack development, from building a frontend with React to handling backend services using Node.js.

### Screenshots 📷
  
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Charul Chim
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)  
GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@Charul00 based on the work i will raise the level accordingly
