### ISSUE TITLE
📃: Add DevOps Resources and Scripts

### ISSUE THREAD

**Issue by Charul00** [UTSAVS26/PyVerse#136]
:red_circle: **Title** :  
Add DevOps Resources and Scripts

:red_circle: **Aim** :  
To provide valuable DevOps resources, including automation scripts, best practices, and tools for effective development, integration, and deployment workflows.

:red_circle: **Brief Explanation** :  
This contribution aims to compile popular DevOps resources and automation scripts that streamline software development, integration, and deployment processes. The resources will cover key areas like CI/CD, containerization, orchestration, configuration management, and monitoring tools. Each script or resource will have a brief explanation of its purpose and usage.

### DevOps Resources & Scripts 🚀

1. **[CI/CD Pipeline with Jenkins](https://example.com/jenkins-pipeline.md)**  
   A step-by-step guide for setting up a CI/CD pipeline using Jenkins. This script automates the build, test, and deployment processes for continuous integration and delivery.

2. **[Dockerized Node.js Application](https://example.com/docker-node-app.md)**  
   A script that demonstrates how to containerize a Node.js application using Docker. It includes instructions on creating a `Dockerfile`, building a Docker image, and running it in a container.

3. **[Kubernetes Deployment Script](https://example.com/kubernetes-deployment.yaml)**  
   This YAML configuration file helps deploy a microservice-based application in a Kubernetes cluster. It includes setting up deployments, services, and scaling for high availability.

4. **[Ansible Playbook for Server Provisioning](https://example.com/ansible-playbook.md)**  
   An Ansible playbook for automating server provisioning and configuration management. It includes tasks for installing software, setting up firewalls, and configuring services.

5. **[Terraform Script for AWS Infrastructure](https://example.com/terraform-aws.md)**  
   A Terraform configuration script that automates the provisioning of AWS infrastructure, including EC2 instances, security groups, and VPCs.

6. **[Automated Backup with Cron and Bash](https://example.com/backup-script.sh)**  
   A Bash script combined with a cron job for scheduling automatic backups of databases or directories. This script compresses files and saves them to a designated location.

7. **[Monitoring with Prometheus and Grafana](https://example.com/prometheus-grafana-setup.md)**  
   A guide and configuration script to set up monitoring for a system using Prometheus for data collection and Grafana for visualizing metrics.

8. **[GitLab CI/CD for Automated Testing](https://example.com/gitlab-ci.md)**  
   A `.gitlab-ci.yml` file that automates testing, building, and deploying applications using GitLab’s CI/CD pipeline.

### Screenshots 📷
  
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Charul Chim
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)  
GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Charul00** [comment]
add label gssoc-ext and level

**Comment by shreyamaheshwari1** [comment]
@UTSAVS26 I want to work on this as the issue is still open. Could you assign me this
