### ISSUE TITLE
🧑‍💻: Landing Page Enhancement

### ISSUE THREAD

**Issue by ezDecode** [UTSAVS26/PyVerse#137]
:red_circle: **Title** : Landing Page Enhancement
:red_circle: **Enhancement Aim** :   Smooth experience
:red_circle: **Changes** : Smooth scrolling, improved aesthetics, and enhanced user interaction.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Akash Choudhury
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSoC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ezDecode** [comment]
Hey, @UTSAVS26! I hope you're doing well! I'm having a bit of trouble finding the index.html file. Would you mind helping me out? I have some advanced Python skills and I'm ready to tackle a few issues I've spotted in the code. Should I jump in and work on this, or would it be better to create a new issue? Thanks a bunch!

**Comment by UTSAVS26** [comment]
> Hey, @UTSAVS26! I hope you're doing well! I'm having a bit of trouble finding the index.html file. Would you mind helping me out? I have some advanced Python skills and I'm ready to tackle a few issues I've spotted in the code. Should I jump in and work on this, or would it be better to create a new issue? Thanks a bunch!

Have you joined the discord server?
