### ISSUE TITLE
📃: Stacks

### ISSUE THREAD

**Issue by TheChaoticor** [UTSAVS26/PyVerse#14]
:red_circle: **Stacks* :
:red_circle: **Add full interpretation and code of stack ** :
:red_circle: **A Stack is a linear data structure that follows a particular order in which the operations are performed. The order may be LIFO(Last In First Out) or FILO(First In Last Out). LIFO implies that the element that is inserted last, comes out first and FILO implies that the element that is inserted first, comes out last.** :

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Arpit Mishra
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
    Mentor,gssoc-ext

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Charul00** [comment]
can you please assign to me

**Comment by TheChaoticor** [comment]
ok

**Comment by Charul00** [comment]
can you please check hactoberfest label is this correct or not in the website having  hacktoberfest-accepted

**Comment by TheChaoticor** [comment]
It's okay. Still the new label will be added

**Comment by TheChaoticor** [comment]
Good

**Comment by Charul00** [comment]
it says this can you know why not considering my submissions

![Screenshot 2024-10-02 174859](https://github.com/user-attachments/assets/5800641b-ed43-4455-ab75-e39e9dbfc1ee)

**Comment by TheChaoticor** [comment]
Wait, let me check. Don't worry, we will revert back to you. Focus on your other PRs

**Comment by TheChaoticor** [comment]
is it in hactoberfest or gssoc?
