### ISSUE TITLE
🧑‍💻: Updating favicon to logo of PyVerse

### ISSUE THREAD

**Issue by nksmanya** [UTSAVS26/PyVerse#145]
The favicon and the logo of the website look different. I would like to change this. 
Please assign this issue to me @UTSAVS26 
Also add the respective level and other labels

**Comment by UTSAVS26** [comment]
@nksmanya can you show me the images or favicon you are planning to do and what you gonna do and how

**Comment by nksmanya** [comment]
Yes @UTSAVS26 
So you can see that there are two different logos in the website. 
One favicon and the other one is 
![logo of pyverse](https://github.com/user-attachments/assets/a1643579-dae4-4df1-9f57-60dac6cea88f)

I have created a new logo and favicon for PyVerse. 
Logo:
![PyVerse logo](https://github.com/user-attachments/assets/4d6502c8-bc31-43af-91cd-40816dc201cd)


Favicon :
![PyVerse favicon](https://github.com/user-attachments/assets/ce408eea-7afe-4d7e-88d5-e3cdb41297ce)

I thought it will be better to have the same kind of logo and favicon, but in the website , both favicon and logo give off different themes.

**Comment by UTSAVS26** [comment]
You can send it to me or any mentors @TheChaoticor or @shaansuraj as i don't think this will be considered as contribution, but you can tag other mentors and ask to assign you this issue if they will then I don't able any problem with that. All the best

**Comment by TheChaoticor** [comment]
I like the logo but i dont think a logo design can be assigned as a contribution
