### ISSUE TITLE
📃:KBC Quiz Game

### ISSUE THREAD

**Issue by ishant025** [UTSAVS26/PyVerse#154]
:red_circle: **Title** : KBC Quiz Game
:red_circle: **Aim** : Provide entertainment through interactive questions, making learning or testing knowledge enjoyable.
:red_circle: **Brief Explanation** : Python code creates a quiz game modeled after Kaun Banega Crorepati (KBC), where players answer multiple-choice questions to win increasing amounts of money.

### Screenshots 📷
![Screenshot 2024-10-06 at 1 09 37 PM](https://github.com/user-attachments/assets/fe35f905-1e49-42dc-b295-a49b3fe4e6b6)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ishant Sahu(ishant025)(https://github.com/ishant025)
- What is your participant role? GSSOC-EXT, Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ishant025** [comment]
Please Assign me.. I am beginner in open source contribution

**Comment by UTSAVS26** [comment]
@ishant025 how many questions will be there in the game and are you calculating the scores too?

**Comment by ishant025** [comment]
> @ishant025 how many questions will be there in the game and are you calculating the scores too?

@UTSAVS26 10 questions

**Comment by ishant025** [comment]
> > @ishant025 how many questions will be there in the game and are you calculating the scores too?
> 
> @UTSAVS26 10 questions

10 questions will be asked from total of 14 questions

**Comment by UTSAVS26** [comment]
Okie
