### ISSUE TITLE
📃: Basic encryption and decryption program

### ISSUE THREAD

**Issue by djv554** [UTSAVS26/PyVerse#178]
:red_circle: **Title** : Basic encryption and decryption program
:red_circle: **Aim** : A simple program that encrypts and decrypts messages using basic algorithms like Caesar cipher or Vigenère cipher.
:red_circle: **Brief Explanation** : The program will take user input and encrypt/ decrypt the message in either Caesar cipher or Vigenère cipher.

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Deanne Vaz
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSoC-extd contributor and Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by djv554** [comment]
@UTSAVS26 should I add this in the Beginner_projects folder or in the Cyber Security tools folder?

**Comment by UTSAVS26** [comment]
> @UTSAVS26 should I add this in the Beginner_projects folder or in the Cyber Security tools folder?

In cybersecurity folder

**Comment by UTSAVS26** [comment]
In cybersecurity folder

**Comment by djv554** [comment]
Okay, thanks!
