### ISSUE TITLE
📃: URL Shortener

### ISSUE THREAD

**Issue by Charul00** [UTSAVS26/PyVerse#191]
:red_circle: **Title** : URL Shortener

:red_circle: **Aim** : To create a simple URL shortener that converts long URLs into shorter versions.

:red_circle: **Brief Explanation** : 
This project involves building a basic URL shortener that takes a long URL as input and generates a shorter, manageable version. It will help you practice string manipulation and data storage techniques, and if you choose to implement a web interface, you can learn about web frameworks as well.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Charul Chim
- What is your participant role? 
- Gssoc-ext

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Rahul-AkaVector** [comment]
Hi, I'd love to contribute to this issue.

🔴 Full Name: Rahul Aka Vector
🔴 Participant Role: SSOC , Hacktoberfest

Looking forward to contributing! 😎

**Comment by UTSAVS26** [comment]
> Hi, I'd love to contribute to this issue.
> 
> 🔴 Full Name: Rahul Aka Vector
> 🔴 Participant Role: SSOC , Hacktoberfest
> 
> Looking forward to contributing! 😎
> 

Bro SSOC ends, which SSOC you are talking about? 
And raise another issue as this issue is going to be assigned to @Charul00

**Comment by UTSAVS26** [comment]
@Charul00 bro please fill all the details in the Template like name, participation roles, etc.

**Comment by Charul00** [comment]
@UTSAVS26  done bro
