### ISSUE TITLE
🧑‍💻: README (Bug fix)

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PyVerse#2]
:red_circle: **Title** : README (Bug-fix):
:red_circle: **Enhancement Aim** : Documentation
:red_circle: **Changes** : Add appropriate markdown syntax for the readme smooth movement

### Screenshots 📷
![PyVerse-bug](https://github.com/user-attachments/assets/75502ca6-1877-41d1-bd20-7ec9a056014c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : [Yash Kumar Saini](https://github.com/yashksaini-coder)
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

Contributor for WoB'24 
***********************************************************************

---
Please add labels and assign this issue to me. @UTSAVS26

**Comment by poorvikaa08** [comment]
I'm Poorvika K B, a contributor in GSSoC extd 2024.

I want to work on this issue.
Thank you.

**Comment by UTSAVS26** [comment]
> I'm Poorvika K B, a contributor in WOB 2024.
> 
> I want to work on this issue.
> Thank you.
> 

You can raise another issue @poorvikaa08

**Comment by UTSAVS26** [comment]
@yashksaini-coder work on this issue and please raise 1 issue at a time so that other Contributors also get a chance to contribute. All the best 👍
