### ISSUE TITLE
📃: Add qr generator

### ISSUE THREAD

**Issue by ananyag309** [UTSAVS26/PyVerse#20]
:red_circle: **Title** : QR generator
:red_circle: **Aim** : Begineer python project 
:red_circle: **Brief Explanation** : This script take a link of any URL and generate a QR code corresponding to it.

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ananya Gupta
- What is your participant role? GSSOC and Hacktober

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@ananyag309 work on 1 issue at a time right now I am putting this issue under `Up for grabs` if no one wants to work on this one then after completing your previous issue comment on this, i will assign this to you. All the best

**Comment by ananyag309** [comment]
@UTSAVS26 i have completed previous issue please assign it to me

**Comment by Pavitra-s-Workspace** [comment]
Uppada Pavitra Manaswini Reddy
GSSoC24' Extended Contributor
Im interested to contribute please assign me.

**Comment by ananyag309** [comment]
@UTSAVS26 sir please assign this issue to me

**Comment by UTSAVS26** [comment]
> Uppada Pavitra Manaswini Reddy
> GSSoC24' Extended Contributor
> Im interested to contribute please assign me.
> 

Sorry but I already have already a plan to assigned you 1 issue that you gonna raise regarding the beginner projects.
