### ISSUE TITLE
Add queue related problem solutio dsa section

### ISSUE THREAD

**Issue by Aditijainnn** [UTSAVS26/PyVerse#210]
:red_circle: **Title** : Queue

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC EXT and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@Aditijainnn what you gonna do in this issue and how? have you joined the discord?

**Comment by rrayhka** [comment]
> @Aditijainnn what you gonna do in this issue and how? have you joined the discord?

I wanna join discord servers, where's the link

**Comment by UTSAVS26** [comment]
> > @Aditijainnn what you gonna do in this issue and how? have you joined the discord?
> 
> I wanna join discord servers, where's the link

https://discord.gg/9mZnkTRFFe
