### ISSUE TITLE
📃: Drowsiness Detection System

### ISSUE THREAD

**Issue by sarthaxtic** [UTSAVS26/PyVerse#217]
:red_circle: **Title** : Drowsiness Detection System
:red_circle: **Aim** : To prevent drivers from accident during night
:red_circle: **Brief Explanation** : Detects whether a driver is awake,drowsy or sleepy while driving. If a driver is sleepy, alarm gets triggered and alerts the driver.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sarthak
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC and Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@sarthaxtic what you gonna do in this issue as one contributor has already raised the issue #151

**Comment by sarthaxtic** [comment]
I have used different libraries than #151

**Comment by UTSAVS26** [comment]
> I have used different libraries than #151

Like what libraries list them.

**Comment by sarthaxtic** [comment]
OpenCV, Dlib, Imutils, Numpy and playsound.
You can consider my project as a lighter version of #151 as it just detects sleepiness and plays alarm, instead of showing percentage.
