### ISSUE TITLE
📃: Data Summarization using NLP

### ISSUE THREAD

**Issue by sarthaxtic** [UTSAVS26/PyVerse#218]
:red_circle: **Title** : Data Summarization using NLP
:red_circle: **Aim** : To provide a summary of a large text using Hugging face
:red_circle: **Brief Explanation** : This project provides a summary of a large text and the summary is generated using Hugging face API.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sarthak
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
- GSSOC and Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by rrayhka** [comment]
full name: akhyar
hacktoberfest

**Comment by UTSAVS26** [comment]
> full name: akhyar
> hacktoberfest

Raise another issue

**Comment by ShreyasSN** [comment]
Hi @sarthaxtic,
Name: Shreyas S N
Hacktoberfest

I had like to work on this, please assign me

**Comment by UTSAVS26** [comment]
> Hi @sarthaxtic,
> Name: Shreyas S N
> Hacktoberfest
> 
> I had like to work on this, please assign me

Sorry, You can raise another issue as this one is already assigned.
