### ISSUE TITLE
📃: 

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [UTSAVS26/PyVerse#22]
:red_circle: **Tree** :
:red_circle: **To implement Binary trees** :
:red_circle: **We can add tree traversals ** :

### Screenshots 📷
<N/A >

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Chiluka Akshitha
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
~GSSOC ,Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@AKSHITHA-CHILUKA please add documentation for traversal techniques too. And tell me what all tree you are gonna cover in this issue? Only basic tree or any other like `BST`, `AVL` or something like that. 
All the best

**Comment by AKSHITHA-CHILUKA** [comment]
Algorithms_and_Data_Structures/
├── Trees/
│   ├── Menu_Driven_Code_for_Binary_Tree.py
│   ├── Menu_Driven_Code_for_Binary_Search_Tree.py
│   ├── Menu_Driven_Code_for_Avl_Tree.py
│   ├── Menu_Driven_Code_for_Tree_Traversals.py
│   ├── Menu_Driven_Code_for_DFS.py
│   ├── Menu_Driven_Code_for_Inorder_Traversal.py
│   ├── Menu_Driven_Code_for_Preorder_Traversal.py
│   ├── Menu_Driven_Code_for_Postorder_Traversal.py
│   ├── README.md

**Comment by AKSHITHA-CHILUKA** [comment]
Shall I start working?

**Comment by UTSAVS26** [comment]
> Shall I start working?

Yeah sure
