### ISSUE TITLE
📃: Add Snake Game

### ISSUE THREAD

**Issue by ishant025** [UTSAVS26/PyVerse#226]
:red_circle: **Title** : Snake Game
:red_circle: **Aim** : Made for fun and exploring 2D game development in Python
:red_circle: **Brief Explanation** : In this game, you control a snake that grows longer every time it eats food, and you have to avoid crashing into the walls or the snake's own body.

### Screenshots 📷
![Screenshot 2024-10-07 at 5 31 26 PM](https://github.com/user-attachments/assets/8de16ff0-7d5a-40c6-b0fd-8a4a965e3ade)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ishant Sahu 
- What is your participant role? GSSOC-EXT , Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ShreyasSN** [comment]
Hi @UTSAVS26,
I had like to work on this issue. I have experience with python and I believe I can contribute effectively.

**Comment by UTSAVS26** [comment]
> Hi @UTSAVS26,
> I had like to work on this issue. I have experience with python and I believe I can contribute effectively. 

You can raise another issue as this one is already assigned.
