### ISSUE TITLE
📃:  Design and Analysis of Algorithms (DAA)

### ISSUE THREAD

**Issue by priyanka350** [UTSAVS26/PyVerse#24]
:red_circle: Design and Analysis of Algorithms (DAA) :
:red_circle: Addition of Design and Analysis of Algorithms under DSA :
:red_circle: Explaining the concepts of dynamic programming, greedy algorithms, divide & conquer, backtracking, shortest path, and all-pair shortest path algorithms, along with providing the code for their real-world applications.

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priyanka Kumari
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) : Gssoc extd. Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@priyanka350 i will add labels based on the work done. Hope you understand.
