### ISSUE TITLE
📃: Add basic real-time chat application

### ISSUE THREAD

**Issue by mehul-m-prajapati** [UTSAVS26/PyVerse#247]
:red_circle: **Title** : Real-time chat application
:red_circle: **Aim** : Create a basic real-time chat application
:red_circle: **Brief Explanation** : Basic real-time chat application

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mehul Prajapati
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) - gssoc and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@mehul-m-prajapati please wait before raising PR, first you need to get yourself assigned in the issue you raised, for now i am approving but for future please remember.
