### ISSUE TITLE
🧑‍💻: Image captioning model

### ISSUE THREAD

**Issue by BhavyaFattania** [UTSAVS26/PyVerse#25]
Image captioning model is Deep learning model based on GAN which generates captions based on image provided by user
It generates conditional and unconditional captions.
user will provide image and the model will generate captions for that.
![Screenshot 2024-10-02 023131](https://github.com/user-attachments/assets/19896a76-c5c7-49c0-a3c5-a468171ea61f)

**Comment by UTSAVS26** [comment]
@BhavyaFattania I am closing this issue and please use `Feature Addition` issue template for adding new features and for now work on 1 issue at a time

**Comment by BhavyaFattania** [comment]
I have made a streamlit app to solve this, please guide me as I am doing this for first time @UTSAVS26

**Comment by UTSAVS26** [comment]
>  I have made a streamlit app to solve this, please guide me as I am doing this for first time @UTSAVS26 
> 

Go to the issues sections and raise a new issue then on that select `Feature Addition` and then fill all the details that are asking in that template.
