### ISSUE TITLE
📃: Sugarcane Leaf Disease Detection

### ISSUE THREAD

**Issue by IkkiOcean** [UTSAVS26/PyVerse#251]
:red_circle: **Title** : Sugarcane Leaf Disease Detection
:red_circle: **Aim** : 
- This project focuses on classifying sugarcane leaf diseases using different machine learning models. The dataset contains images of sugarcane leaves classified into various categories. Image preprocessing, data augmentation, and ensemble learning methods are applied to boost the model’s accuracy.
Feature Description

:red_circle: **Brief Explanation** :

- Add a Jupyter notebook implementing an ensemble model for sugarcane disease prediction.
- Combine multiple deep learning architectures: MobileNet, InceptionV3, VGG16, Conv2D, and ResNet152 into a cohesive model.
- Implement data preprocessing steps, including image augmentation and normalization.
- Conduct model training and evaluation, achieving an overall high accuracy 
- Included detailed comments and explanations throughout the notebook for clarity and reproducibility.
- Visualized model performance metrics and comparison graphs for individual models.

### Screenshots 📷
![input](https://github.com/user-attachments/assets/c3bafaa9-cc84-42ca-9bed-12c8c3e926d9)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vivek Prakash
- What is your participant role? 
 Gssoc-ext and hacktoberfest
***********************************************************************
### Pls assign me level 3 as I will be implementing 5-6 deep learning models for ensemble model

**Comment by UTSAVS26** [comment]
@IkkiOcean based on the work i will update the labels, don't worry about it. Just keep contributing
