### ISSUE TITLE
🧑‍💻: Implement Auto-Labeling Workflow for GitHub

### ISSUE THREAD

**Issue by samyak-aditya** [UTSAVS26/PyVerse#259]
:red_circle: **Title** :  Implement Auto-Labeling Workflow for GitHub
:red_circle: **Enhancement Aim** : This workflow will automatically apply labels "gssoc-ext" and "hacktoberfest-accepted" to issues and pull requests
:red_circle: **Changes** : 

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Samyak Aditya
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC and Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@samyak-aditya if you are creating a workflow, then make it like this that whosoever have added their participation role as GSSOC in that only they add label as it will cause problem as some contributors are only Hacktoberfest not GSSOC ones. 

If you can do so i will assign this issue to you to work on.

**Comment by samyak-aditya** [comment]
okay @UTSAVS26 assign this to me I will work on this

**Comment by samyak-aditya** [comment]
Hey @UTSAVS26 I would highly appreciate if you assigned this task level2

**Comment by samyak-aditya** [comment]
Hey @UTSAVS26 I have raise the PR
