### ISSUE TITLE
📃: Handwritten Math Equation Solver

### ISSUE THREAD

**Issue by Stuti333** [UTSAVS26/PyVerse#283]
:red_circle: Handwritten Math Equation Solver 
:red_circle: Develop a system that can recognize and interpret handwritten mathematical equations from images. Convert the recognized equations into a machine-readable format. Solve the interpreted equations and provide the solution to the user.
:red_circle: System that recognizes handwritten mathematical equations from images, interpret their structure, and solve them automatically. It combines computer vision and natural language processing techniques to bridge the gap between human-written math and computer-solved problems. 

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Stuti Sharma
- What is your participant role? GSSOC and HACKTOBERFEST

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@Stuti333 based on the work done I will update the level.

**Comment by Stuti333** [comment]
Sure
