### ISSUE TITLE
📃: Add Stack Implementation and Variants

### ISSUE THREAD

**Issue by ananyakaligal** [UTSAVS26/PyVerse#285]
We will be adding a comprehensive stack implementation along with its variants to enhance  Algorithms and Data Structures.

The proposed additions will include:

A basic stack implementation with essential operations:

Push
Pop
Peek
IsEmpty

Also, the variants of stack:
Min Stack:
Max Stack
Stack with Frequency Count
Stack using Linked List

**Comment by Sai-ganesh-0004** [comment]
Hello I would like to work on this Can you assign it to me
