### ISSUE TITLE
🧑‍💻: Add crousel 

### ISSUE THREAD

**Issue by shubhagarwal1** [UTSAVS26/PyVerse#290]
Implement a carousel feature on the page to display media or content in a rotating fashion. The carousel should support:

Multiple slides with image and text content.
User controls (next/prev buttons, indicators).
Optional autoplay feature with adjustable interval.
Responsiveness for mobile and desktop views.
hey @UTSAVS26 please assign this task to me

**Comment by UTSAVS26** [comment]
@shubhagarwal1 please use the dedicated Issue Template and fill all the details in it for this issue. I am closing this one.
