### ISSUE TITLE
🧑‍💻: Add Scroll-to-Top Button

### ISSUE THREAD

**Issue by shubhagarwal1** [UTSAVS26/PyVerse#291]
Implement a "Scroll-to-Top" button to allow users to easily navigate back to the top of the page. The button should:

Appear when the user scrolls down beyond a certain point.
Be positioned in a fixed location, such as the bottom right corner.
Include smooth scrolling functionality when clicked.
Be responsive and visually consistent with the overall design of the page.

Hey @UTSAVS26 please asssign this task to me

**Comment by UTSAVS26** [comment]
@shubhagarwal1 same thing as said in previous issue.
