### ISSUE TITLE
📃: Rename Files and Add More LinkedList variants

### ISSUE THREAD

**Issue by ananyakaligal** [UTSAVS26/PyVerse#294]
Description:
I will rename the linked list code files for clarity and add a few variants of linked lists.

Proposed Changes:
Rename Files:

Update file names to be more descriptive, e.g.:
Menu_Driven_Circular_Doubly_LinkedList.py
Menu_Driven_Circular_LinkedList.py
Menu_Driven_Doubly_LinkedList.py
Add Variants:

Include the following linked list variants:
Circular Linked List
Doubly Linked List
Circular Doubly Linked List

**Comment by UTSAVS26** [comment]
@ananyakaligal please use a feature addition template for this issue. I am closing this one
