### ISSUE TITLE
📃: Build & Deploy a Static Webpage

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PyVerse#3]
:red_circle: **Title** :Build & Deploy a Static Webpage:
:red_circle: **Aim** : To build & deploy a basic static webpage that can enhance the overall project for the new contributors 
:red_circle: **Brief Explanation** : Build and deploy a static webpage that presents the repository, its features, and usage instructions.
The page should be easy to navigate and accessible for users wanting to learn more about the project.

### Screenshots 📷

- Something like this
![image](https://github.com/user-attachments/assets/18ecf3f2-5912-4354-95f0-e0ddffb01999)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : [Yash Kumar Saini](https://github.com/yashksaini-coder)
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

Contributor for WoB'24 
***********************************************************************

---
Please add labels and assign this issue to me. @UTSAVS26

**Comment by LearnWithNewton** [comment]
Full name : [MD SARFARAZ](https://github.com/LearnWithNewton)
Participant role : GSSOC Contributor

Can you assign this issue to me?

**Comment by Charvi-14** [comment]
Full name : [Charvi Arora](https://github.com/Charvi-14)
Participant role : GSSOC Contributor

Can you assign this issue to me?

**Comment by Monalisa0311** [comment]
Full name : [Monalisa Biswas](https://github.com/Monalisa0311)
Participant role : GSSOC Contributor

Can you assign this issue to me?

**Comment by UTSAVS26** [comment]
@yashksaini-coder I am assigning this issue to @LearnWithNewton , @yashksaini-coder you can raise other issues and right now you are also working on one issue too.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder I am assigning this issue to @LearnWithNewton , @yashksaini-coder you can raise other issues and right now you are also working on one issue too.

fine 👍🏼

**Comment by yashksaini-coder** [comment]
@UTSAVS26 Well i agree but if no progress is made then I will be raising PR for this issue,

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Well i agree but if no progress is made then I will be raising PR for this issue, 

Sure then I will definitely assign this issue to you

**Comment by yashi-025** [comment]
Can anyone pls explain what is this hacktoberfest

**Comment by UTSAVS26** [comment]
> Can anyone pls explain what is this hacktoberfest

It is like open source contribution program like GSSOC and WoB and SSOC and many others. The thing is it only comes in October. You can read about it here https://hacktoberfest.com/ .

**Comment by yashksaini-coder** [comment]
> > Can anyone pls explain what is this hacktoberfest
> 
> It is like open source contribution program like GSSOC and WoB and SSOC and many others. The thing is it only comes in October. You can read about it here https://hacktoberfest.com/ .

But staged to a international level

**Comment by yashi-025** [comment]
Thanks for updating

**Comment by LearnWithNewton** [comment]
> @yashksaini-coder I am assigning this issue to @LearnWithNewton , @yashksaini-coder you can raise other issues and right now you are also working on one issue too.

@UTSAVS26 : I've stared and forked the repo to work on the issue #3 

Looking for some clarification on these points:

🔴 Title :Build & Deploy a Static Webpage:
- this required for repository, its features, and usage instructions 
- but is it ok if I also add details about individual topics e.g., 
![image](https://github.com/user-attachments/assets/383cd18f-1ccb-417d-a76c-000af478d4f8)

**Comment by UTSAVS26** [comment]
> > @yashksaini-coder I am assigning this issue to @LearnWithNewton , @yashksaini-coder you can raise other issues and right now you are also working on one issue too.
> 
> @UTSAVS26 : I've stared and forked the repo to work on the issue #3 
> 
> Looking for some clarification on these points:
> 
> 🔴 Title :Build & Deploy a Static Webpage:
> - this required for repository, its features, and usage instructions 
> - but is it ok if I also add details about individual topics e.g., 
> ![image](https://github.com/user-attachments/assets/383cd18f-1ccb-417d-a76c-000af478d4f8)
> 


Yeah you can add details also and anything you like but it should align well with the projects. And tell me how you are gonna make the static website using which tech stack or website and how you are going to deploy it? As afterwards I need to be one to deploy it so that i can make necessary changes and work on the deploy too if any issue occurs later on.
