### ISSUE TITLE
📃: Twitter Sentiment Analysis

### ISSUE THREAD

**Issue by aviralgarg05** [UTSAVS26/PyVerse#30]
:red_circle: **Title** :Twitter Sentiment Analysis
:red_circle: **Aim** : Analysis of Tweet Sentiment using NLP and Machine Learning
:red_circle: **Brief Explanation** : Analysis of Tweet Sentiment using NLP and Machine Learning. Will use tweet datasets, wordcloud and ml algorithms to perform the following.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aviral Garg
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC'24 Extended and Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Abhicoder03** [comment]
@UTSAVS26 Hey!, I found this issue interesting. Can I also work on this?

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Hey!, I found this issue interesting. Can I also work on this?
> 

Sorry bro but this issue has already been assigned, you can create a new issue.
