### ISSUE TITLE
📃: Automatic number plate recognition system using image processing

### ISSUE THREAD

**Issue by riyarane46** [UTSAVS26/PyVerse#307]
:red_circle: **Title** : Automatic number plate recognition system using image processing
:red_circle: **Aim** : To develop an automatic number plate recognition (ANPR) system using image processing techniques that can accurately detect and extract vehicle license plates from images or video streams and convert the alphanumeric characters into machine-readable text.

:red_circle: **Brief Explanation** : The Automatic Number Plate Recognition (ANPR) system is designed to recognize vehicle registration plates through image processing techniques. This project involves capturing images or video frames of vehicles, detecting the license plate region, and using Optical Character Recognition (OCR) to read the alphanumeric characters. The system can be applied in various use cases such as traffic monitoring, law enforcement, parking management, and toll systems. Image preprocessing methods like grayscale conversion, edge detection, and contour identification are key to improving the system's accuracy.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Riya Rane
- What is your participant role? - GSSOC , Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@riyarane46 sorry but this project has already been done https://github.com/UTSAVS26/PyVerse/tree/main/Image%20processing%2FNumber%20plate%20detection

If you have anything else you want to add or new project you can raise another issue as i am closing this one
