### ISSUE TITLE
📃: (GenAI Beginners)Build a Generatively Pretrained Transformer (GPT) referring to "Attention is All You Need", OpenAI GPT-2, and Shakespeare Dataset

### ISSUE THREAD

**Issue by shaansuraj** [UTSAVS26/PyVerse#31]
:red_circle: **Title** : Build a Generatively Pretrained Transformer (GPT) referring to "Attention is All You Need", OpenAI GPT-2, and Shakespeare Dataset
:red_circle: **Aim** : Generating the next word based on the context of the previous ones.
:red_circle: **Brief Explanation** : Make use of Self Attention mechanisms to process and generate text efficiently, without relying on recurrent neural networks. You have to refer to "Attention is All You Need" paper and learn about GPT models, like OpenAI's GPT-2, which are pretrained on large text corpora, learning to predict the next word in a sentence, which allows them to generate coherent and contextually relevant text. You can start with Shakespeare's Dataset, the model learns the patterns specific to the playwright’s language, enabling it to generate text in a similar style. This combination of large-scale pretraining and fine-tuning on domain-specific data makes GPT highly effective for creative text generation tasks. This will be your first step towards Generative AI.

Here are the links for your help:

Attention is All You Need: https://arxiv.org/abs/1706.03762
Shakespeare Plays Dataset: https://www.kaggle.com/datasets/kingburrito666/shakespeare-plays

For any issues you can reach me out via email: suraj@brandladder.co.in

### Screenshots 📷
![image](https://github.com/user-attachments/assets/d8fe3a5a-d6bc-4ff7-8c67-fe680f5dc23a)

![image](https://github.com/user-attachments/assets/d184b131-56fd-455f-a4a3-930a0dc73736)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Suraj Sahu 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC'24 Extended and Hacktoberfest Mentor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Abhicoder03** [comment]
@shaansuraj Hey! I found this interesting. Can I work on this issue? Could you please assign this to me.

**Comment by Abhicoder03** [comment]
Hey I found this issue interesting. Could you assign this issue to me.

**Comment by shaansuraj** [comment]
@Abhicoder03 I am glad that you found this topic interesting. I have assigned it to you. If you have any doubts, you can reach me out through the email I provided above.

**Comment by JahnaviDhanaSri** [comment]
Hi @Abhicoder03 
I’m interested in contributing to the Build a Generatively Pretrained Transformer (GPT) project. I plan to focus on:

Understanding Self-Attention Mechanisms, I will thoroughly study the "Attention is All You Need" paper and the architecture of OpenAI's GPT-2 to grasp how self-attention enables efficient text generation.
I will work with the Shakespeare Dataset to learn and emulate the unique language patterns of the playwright, enhancing the model's text generation capabilities.
I will implement the GPT model, ensuring it generates coherent and contextually relevant text based on the context of previous words.

**Comment by shaansuraj** [comment]
@JahnaviDhanaSri Okay sure, I will assign you to this issue as well. You can work collaboratively with @Abhicoder03 on this.

**Comment by JahnaviDhanaSri** [comment]
Thank You!

**Comment by Abhicoder03** [comment]
@JahnaviDhanaSri Hey, we can collaborate on this project.

**Comment by JahnaviDhanaSri** [comment]
Sure!
