### ISSUE TITLE
📃: Sudoku solver web development project

### ISSUE THREAD

**Issue by riyarane46** [UTSAVS26/PyVerse#312]
:red_circle: **Title** : Sudoku Solver Web Development Project
:red_circle: **Aim** : To develop a web application that allows users to input a Sudoku puzzle and provides an instant solution using a backtracking algorithm.
:red_circle: **Brief Explanation** : This project involves creating a web-based Sudoku solver that enables users to enter a Sudoku puzzle and have it solved automatically. The web application will feature a user-friendly interface with a grid for puzzle input and a button to trigger the solution process. The core functionality will rely on a backtracking algorithm to find the solution. The app will be built using HTML, CSS, and JavaScript for the frontend 

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Riya Rane
- What is your participant role? GSSOC , HACTOBERFEST

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Shalinis19137** [comment]
Can you please assign me this project under Gssoc-ext 2024

**Comment by UTSAVS26** [comment]
> Can you please assign me this project under Gssoc-ext 2024

You can raise another issue as this issue has already been assigned and completed.
