### ISSUE TITLE
📃: Backtracking problems  DSA 

### ISSUE THREAD

**Issue by riyarane46** [UTSAVS26/PyVerse#313]
:red_circle: **Title** : Backtracking problems  DSA folder
:red_circle: **Aim** : To provide a collection of Data Structures and Algorithms (DSA) problems solved using backtracking, showcasing its power in solving combinatorial and decision-making problems.
:red_circle: **Brief Explanation** : This folder contains multiple problems and their solutions implemented using the backtracking algorithm in various programming languages (primarily Python). Backtracking is a problem-solving technique used for exploring all potential solutions by building a solution incrementally and removing solutions that fail to satisfy the problem constraints. The problems include classics like Sudoku solver, N-Queens, and others involving permutations, combinations, and pathfinding. These solutions will help learners understand how to approach complex problems using backtracking.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Riya Rane
- What is your participant role? GSSOC , HACKTOBERFEST

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@riyarane46 what all you are going to cover on this issue? As we have already have a Backtracking algorithms folder you can check our [repo structure](https://github.com/UTSAVS26/PyVerse/blob/main/Repo-structure.md) for it.
