### ISSUE TITLE
📃: Greedy algorithm folder

### ISSUE THREAD

**Issue by riyarane46** [UTSAVS26/PyVerse#314]
:red_circle: **Title** : Greedy Algorithm Problems - DSA Codes
:red_circle: **Aim** : To provide a collection of Data Structures and Algorithms (DSA) problems solved using the greedy algorithm, demonstrating its application in optimization problems.
:red_circle: **Brief Explanation** : This folder contains various DSA problems solved using the greedy algorithm. Greedy algorithms work by choosing the best option at each step with the hope of finding the global optimum. The problems include well-known scenarios such as the activity selection problem, fractional knapsack, Huffman coding, and minimum spanning tree (using Prim's and Kruskal's algorithms). These solutions will help learners understand how to apply the greedy technique to solve optimization and decision-making problems efficiently.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Riya Rane
- What is your participant role? GSSOC , HACTOBERFEST

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@riyarane46 what all you are going to cover on this issue? As we have already have a greedy algorithms folder you can check our [repo structure](https://github.com/UTSAVS26/PyVerse/blob/main/Repo-structure.md) for it.
