### ISSUE TITLE
📃: Plant disease detection

### ISSUE THREAD

**Issue by Mayank202004** [UTSAVS26/PyVerse#32]
:red_circle: **Title** : Plant Disease Detection
:red_circle: **Aim** : To help farmers detect plant disease easily with images
:red_circle: **Brief Explanation** : We would be training multiple tensorflow models with help of keras and further we can deploy the resultant models onto web or app platform for easy detection of plant disease.

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mayank Sachin Chougale
- What is your participant role? GSSOC Ext

***********************************************************************

**Comment by Mayank202004** [comment]
Please assign me, this project will be added under deep learning

**Comment by UTSAVS26** [comment]
> Please assign me, this project will be added under deep learning

I have assigned it to you
