### ISSUE TITLE
📃: Online voting system based on PHP and MySQL in Web Development Directory

### ISSUE THREAD

**Issue by LitZeus** [UTSAVS26/PyVerse#320]
:red_circle: **Title** : Online voting system based on PHP and MySQL
:red_circle: **Aim** : To introduce PHP and MySQL in Web Development
:red_circle: **Brief Explanation** : To understand how PHP and MySQL can be used to make web development projects by learning MySQL database connectivity and XAMPP

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Tejas Athalye
- Participating as a `GSSoc-extd | Contributor`

**Comment by UTSAVS26** [comment]
@LitZeus what all tech stack you are going to use in this issue?

**Comment by LitZeus** [comment]
@UTSAVS26 PHP, CSS, SQL

**Comment by UTSAVS26** [comment]
> @UTSAVS26 PHP, CSS, SQL
> with admin login and voter login, and candidate and voter registration features

Will you be able to use Python? As this repo mainly focuses on Python.

**Comment by LitZeus** [comment]
@UTSAVS26 I will try and address the same with a new issue!
#### Thank you

**Comment by UTSAVS26** [comment]
So do I assign this issue to you or close this one?

**Comment by LitZeus** [comment]
close this one
