### ISSUE TITLE
📃: Rock, Paper, Scissor Game

### ISSUE THREAD

**Issue by icemberg** [UTSAVS26/PyVerse#321]
:red_circle: **Title** :  Rock, Paper, Scissors Game
:red_circle: **Aim** :The aim of the Rock, Paper, Scissors game is to defeat your opponent by selecting an option (rock, paper, or scissors) that beats the symbol chosen by the other player.
:red_circle: **Brief Explanation** :The aim of the Rock, Paper, Scissors game is to defeat your opponent by selecting an option (rock, paper, or scissors) that beats the symbol chosen by the other player, based on the following simple rules:

Rock beats Scissors: Rock crushes Scissors.
Scissors beat Paper: Scissors cut Paper.
Paper beats Rock: Paper covers Rock.

In each round of the game, both players choose their symbol at the same time. The winner of the round is determined based on the above rules. If both players choose the same symbol, the round is a tie. The game can be played for a single round or multiple rounds, with the player winning the most rounds being declared the overall winner.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Abhiraam S
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
Participating in Open Source Programs GSSOC extd 24, Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Shalinis19137** [comment]
Hello Sir , I would like to work on this project ,Can you plese assign me this project

**Comment by icemberg** [comment]
This is already assigned check for another project

**Comment by icemberg** [comment]
this game has already been implemented 2 days ago . I don't know how it got assigned to somebody else... but I want to add gui for the game can you please assign this task
