### ISSUE TITLE
📃: Implementing Machine Learning Models for Weather Prediction and Analysis  

### ISSUE THREAD

**Issue by BenakDeepak** [UTSAVS26/PyVerse#322]
### :red_circle: **Title**:  
Implementing Machine Learning Models for Weather Prediction and Analysis  

### :red_circle: **Aim**:  
To build and compare various machine learning models (both regression and classification) using a weather prediction dataset, evaluating the performance of each model based on key metrics like accuracy and mean squared error.

### :red_circle: **Brief Explanation**:  
The goal of this project is to implement and compare 10 different machine learning models for classification and regression tasks. The weather dataset is used to predict continuous variables such as temperature (regression) and binary conditions such as BBQ weather (classification). Models such as Logistic Regression, Random Forest, SVM, k-NN, Neural Networks, and Gradient Boosting are evaluated to determine their accuracy for classification tasks, while regression models are evaluated based on the Mean Squared Error (MSE). The preprocessing steps include handling missing values, splitting the dataset, and standardizing features.  

### Screenshots 📷  
  
N/A

***********************************************************************  
:white_check_mark: **To be Mentioned while taking the issue**:  
- Full name: Benak Deepak 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************  
Happy Contributing 🚀  
All the best. Enjoy your open-source journey ahead. 😎

**Comment by UTSAVS26** [comment]
Sorry @BenakDeepak but this project is under progress https://github.com/UTSAVS26/PyVerse/issues/180.
You can tell what all you are adding or raise a new issue for new project.
