### ISSUE TITLE
📃: Adding 'Video Foresnsic Analysis Tool' to Cybersecurity Tools directory

### ISSUE THREAD

**Issue by LitZeus** [UTSAVS26/PyVerse#323]
:red_circle: **Title** : Video Foresnsic Analysis Tool
:red_circle: **Aim** : To maintain video content integrity and check for tampering of its content
:red_circle: **Brief Explanation** : The Video Forensic Analysis Tool is designed to ensure video authenticity and integrity by addressing manipulation challenges. It utilizes advanced algorithms for metadata examination, watermark authentication, image and audio analysis, deepfake detection, and frame interpolation identification. The tool generates detailed reports, providing visual representations of findings, making it essential for professionals in law enforcement and journalism to safeguard the truth in visual media.

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Tejas Athalye
- Participating as a `GSSoc-extd | Contributor`

**Comment by Shalinis19137** [comment]
I would like to work with you can you plese assign me this project under Gssoc-ext 2024.

**Comment by UTSAVS26** [comment]
> I would like to work with you can you plese assign me this project under Gssoc-ext 2024.
> 

Raise a new issue.
