### ISSUE TITLE
📃: 

### ISSUE THREAD

**Issue by AHSANATIQ98** [UTSAVS26/PyVerse#324]
:red_circle: **Collecting and analysing Weather data using APIs** :
:red_circle: **Addition to data analysis folder** :
:red_circle: **The project collects data from open weather maps website API and it is merged with dataset of cities. After collecting An EDA is performed
 ** :

### Screenshots 📷

![Temparture](https://github.com/user-attachments/assets/c2404247-47b3-46b6-9320-eb64a33080b8)
![temprature vs humdidity scatter](https://github.com/user-attachments/assets/82a906d0-0def-4572-ade6-9f063e8c5aab)
![Weater distribution](https://github.com/user-attachments/assets/094bf756-94b3-451c-8356-b0dc3150ea56)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Muhammad Ahsan Atiq
- What is your participant role? (Mention the Open Source Program name. gssoc-ext

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
Sorry @AHSANATIQ98 but this project is under progress https://github.com/UTSAVS26/PyVerse/issues/180.
You can tell what all you are adding or raise a new issue for new project.
