### ISSUE TITLE
📃: 

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [UTSAVS26/PyVerse#33]
:red_circle: **ADD new project** :
:red_circle: **Multivitamine prediction** :
:red_circle: **deployed a model in azure with 80 % accuracy** :

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Chiluka Akshitha
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
Gssoc  and hactoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
Hi @AKSHITHA-CHILUKA please make sure to raise 1 issue at a time and when it's PR get merged then raise another issue. Right now I am putting this usse under `Up for Grabs and after you don't with your previous issue, tag me here I will assign this issue to you . 

Best of luck 🍀

**Comment by yashi-025** [comment]
Can you assign this to me.

**Comment by AKSHITHA-CHILUKA** [comment]
@UTSAVS26 I have completed my previous issue can you assign me this issue

**Comment by UTSAVS26** [comment]
@yashi-025 you can raise another issue . All the best

**Comment by AKSHITHA-CHILUKA** [comment]
I have the selenium code and already scrapped data as a excel 
Should I upload them both

**Comment by UTSAVS26** [comment]
> I have the selenium code and already scrapped data as a excel 
> Should I upload them both

Yeah sure.
