### ISSUE TITLE
📃: Addition of FastAPI Control Panel

### ISSUE THREAD

**Issue by Shariq2003** [UTSAVS26/PyVerse#336]
:red_circle: **Title** : Addition of FastAPI Control Panel
:red_circle: **Aim** : Addition of FastAPI Control Panel
:red_circle: **Brief Explanation** :

Pythons FASTAPI projects for CRUD operation of users by admin.
Tech Stack : React, FastAPI, MYSQL, and Radis for caching.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shariq
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC Ext
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@Shariq2003 will you be able to integrate Python as Python is the main source of this repo.
