### ISSUE TITLE
📃: Dynamic programming more problems 

### ISSUE THREAD

**Issue by riyarane46** [UTSAVS26/PyVerse#359]
:red_circle: **Title** : Dynamic Programming – Additional Problems
:red_circle: **Aim** :To enhance the PyVerse repository by adding more dynamic programming problems and solutions, covering popular concepts in dynamic programming.
:red_circle: **Brief Explanation** : Climbing Stairs Problem: A problem that determines the number of ways to reach the top of a staircase with n steps, where at each step you can either climb 1 or 2 stairs.
Target Sum Subset: Given an array of integers, this problem finds whether a subset of the array sums up to a given target value.
Coin Change Problem: This problem computes the minimum number of coins required to make a specific amount from given denominations.
Catalan Numbers: Catalan numbers are a sequence of natural numbers with applications in combinatorial mathematics, such as calculating the number of ways to correctly match parentheses, binary trees, and more.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Riya Rane
- What is your participant role? GSSOC , HACTOBERFEST

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Harshitraaaj** [comment]
let me assigned this issue

**Comment by UTSAVS26** [comment]
@Harshitraaaj sorry but this issue has been assigned to that contributor who raised it. You can raise another issue.
