### ISSUE TITLE
📃: Add Tic-tac-toe game in python

### ISSUE THREAD

**Issue by mehul-m-prajapati** [UTSAVS26/PyVerse#361]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [x] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/248

### Project Description

 Tic-tac-toe, noughts and crosses, or Xs and Os is a paper-and-pencil game for two players who take turns marking the spaces in a three-by-three grid with X or O. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row is the winner.

### Full Name

Mehul Prajapati

### Participant Role

GSSOC

**Comment by snehas-05** [comment]
Heyy I would love to add tic-tac-toe game in your repo. Please assign me this task @UTSAVS26

**Comment by UTSAVS26** [comment]
> Heyy I would love to add tic-tac-toe game in your repo. Please assign me this task @UTSAVS26 

@snehas-05 you can raise another issue.
