### ISSUE TITLE
📃: Add minesweeper game in python

### ISSUE THREAD

**Issue by mehul-m-prajapati** [UTSAVS26/PyVerse#363]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

#248

### Project Description

In this classic game of "Minesweeper," you uncover tiles on a grid while avoiding hidden mines. Each tile reveals either a number (indicating how many mines are adjacent) or a mine itself. Your goal is to clear the board without hitting any mines!

### Full Name

Mehul Prajapati

### Participant Role

GSSOC

**Comment by snehas-05** [comment]
hey I would love to add this game. please assign me this task.

**Comment by UTSAVS26** [comment]
@mehul-m-prajapati read the guidelines first in discussion page. And @snehas-05 please raise another issue for the same if you want to work in this as I am closing this one based on the rules.
