### ISSUE TITLE
[Code Addition Request]:  Age Detection Using Deep learning OpenCv

### ISSUE THREAD

**Issue by ramana2074** [UTSAVS26/PyVerse#370]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#91

### Project Description

i would like to detect Age by using Cascade Classifier which is a pretrained model. The age weights and cfg are also used so that the ages are perfectly can be divided into a certain class intervals (1-5,6-12,etc).

### Full Name

Venkata Ramana

### Participant Role

GSSOC Extended Contributor

**Comment by UTSAVS26** [comment]
@ramana2074 I am closing this issue based on the rules, you can read them in discussion page pin posts.
