### ISSUE TITLE
Terrain classification model using transfer learning

### ISSUE THREAD

**Issue by DarshAgrawal14** [UTSAVS26/PyVerse#374]
hey @UTSAVS26 !
I am Darsh Agrawal , a fellow contributor and I would like to contribute by using Transfer learning and create a model to help various agencies label captured terrain images like mountains, coast , desserts etc . By using transfer learning we can use pre trained models like RESNET or Efficientnet and hyperparameter tune them for terrain classification for better accuracy when compared to traditional CNN models.

**Comment by UTSAVS26** [comment]
@DarshAgrawal14 I am closing this issue as you didn't use proper issue template for the same, please use them to raise this issue again .
