### ISSUE TITLE
[Code Addition Request]: Add gem cruncher game

### ISSUE THREAD

**Issue by Aditijainnn** [UTSAVS26/PyVerse#377]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

Add gem cruncher game similar to that candy crush

### Project Description

Assign this to me under gssoc ext and hacktoberfest

### Full Name

Aditi

### Participant Role

Contributor

**Comment by Keshabkjha** [comment]
@UTSAVS26 Can you assign this to me ?

**Comment by UTSAVS26** [comment]
@Aditijainnn please fill proper details what all is asked nothing else, I am closing this issue . 


@Keshabkjha don't comment on any open issue until it is label as `Up for Grabs`, you can raise a new issue.
