### ISSUE TITLE
[Code Addition Request]: Terrain classification model using transfer learning

### ISSUE THREAD

**Issue by DarshAgrawal14** [UTSAVS26/PyVerse#385]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PySnippets/pull/42

### Project Description

hey @UTSAVS26 !
I am Darsh Agrawal , a fellow contributor and I would like to contribute by using Transfer learning and create a model to help various agencies label captured terrain images like mountains, coast , desserts etc . By using transfer learning we can use pre trained models like RESNET or Efficientnet and hyperparameter tune them for terrain classification for better accuracy when compared to traditional CNN models.

### Full Name

Darsh Agrawal

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
Don't add PySnippets Project here it is different project.

**Comment by Sai-ganesh-0004** [comment]
Hello I would like to work on this Can you assign it to me
