### ISSUE TITLE
[Code Addition Request]: Time Series Analysis using ARIMA for stock prediction

### ISSUE THREAD

**Issue by DarshAgrawal14** [UTSAVS26/PyVerse#386]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PySnippets/pull/42

### Project Description

hey @UTSAVS26
I would like to contribute by adding a time series analysis model for stock prediction as most the models found on internet use LSTM or other regression models and do not take the day of exchange into account . This model by taking date and dividing it into day, month and year along with lags. A dataset found on internet was upgraded to support time series analysis and a ARIMA model is trained on it.

### Full Name

Darsh Agrawal

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@DarshAgrawal14 read guidelines as I say before you can raise 1 issue at a time.
