### ISSUE TITLE
[Code Addition Request]: 💡 Adding Diabetes detection model using 3 ensemble models in Machine_learning directory

### ISSUE THREAD

**Issue by LitZeus** [UTSAVS26/PyVerse#388]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### They both are left to review and merge

https://github.com/UTSAVS26/PyVerse/pull/331

https://github.com/UTSAVS26/PyVerse/pull/318

### Diabetes detection model using 3 ensemble models involves building a machine learning system to detect diabetes using the Pima Indians Diabetes dataset from Kaggle. The system incorporates three ensemble models:

- Stacking model: Combines multiple classifiers and uses another model to aggregate the predictions.
- Soft voting model: Takes the weighted average of predicted probabilities from different models.
- Hard-soft voting model: Incorporates both hard voting (majority class prediction) and soft voting (probability-based averaging) strategies.

### Full Name

Tejas Athalye

### Participant Role

`GSSoc-extd | Contributor` , `Hacktoberfest`

**Comment by UTSAVS26** [comment]
@LitZeus I am assigning this issue but please wait before raising any new issue until your PR is merged.

**Comment by LitZeus** [comment]
@UTSAVS26 okay, sure
