### ISSUE TITLE
[Code Addition Request]: Add Recipe Manager in advanced projects

### ISSUE THREAD

**Issue by mehul-m-prajapati** [UTSAVS26/PyVerse#390]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/248

### Project Description

An app that allows users to store, organize, and share their favorite recipes, with features like meal planning and grocery lists.

### Full Name

Mehul Prajapati

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@mehul-m-prajapati have you completed all the issues you were assigned before alongwith all the pr have been merged?

**Comment by mehul-m-prajapati** [comment]
> @mehul-m-prajapati have you completed all the issues you were assigned before alongwith all the pr have been merged? I have closed your other issue based on rule you can read them on discussion page.

@UTSAVS26 : okay, I have updated all pending PR reviews. I can work on this issue from now.
