### ISSUE TITLE
[Code Addition Request]: Drum Kit game

### ISSUE THREAD

**Issue by priyashuu** [UTSAVS26/PyVerse#397]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

NA

### Project Description

The Drum Kit is an interactive web application that allows users to play various drum sounds using both mouse clicks and keyboard inputs. It features seven different types of drum sounds, each associated with a unique button on the screen and a corresponding key on the keyboard.

Features
Seven Drum Sounds: The kit includes seven distinct drum sounds, providing a rich and varied drumming experience.
Interactive Play: Users can play the drum sounds by either clicking on the on-screen buttons or pressing specific keys on their keyboard.

### Full Name

priya Rani

### Participant Role

GSSOC , HACKOCTOBERFEST,WOB'24

**Comment by UTSAVS26** [comment]
@priyashuu are you integrating python in this project or not?

**Comment by priyashuu** [comment]
no , i contributed in web dev section

**Comment by UTSAVS26** [comment]
> no , i contributed in web dev section

Sorry then this project can't be merged as new guidelines we have added in discussion page only the projects that are using python (in wed dev section too) are only accepted. If you can try to integrate Python then it is good, otherwise we need to close this one.

**Comment by priyashuu** [comment]
is it a problem?

**Comment by priyashuu** [comment]
i can add another game

**Comment by priyashuu** [comment]
which is developed in python .. can i ?

**Comment by priyashuu** [comment]
i can delete these commit , add some other files .. can i ?

**Comment by UTSAVS26** [comment]
> which is developed in python .. can i ?

Yes you can add this, the main goal of repo is to use python in different domains and show how it can be integrated with them, right now I am deleting some projects too that don't have python in them.

**Comment by priyashuu** [comment]
ok ok

**Comment by UTSAVS26** [comment]
> i can delete these commit , add some other files .. can i ?

If the game you are creating with python is same as the issue then you can change your commit otherwise you can raise one for that specific game, we will close this one.

**Comment by priyashuu** [comment]
ok , close this one , im adding another game

**Comment by priyashuu** [comment]
can you please assign this one ,#507
