### ISSUE TITLE
📃: Adding Workflows to Update Directory Structure in Real Time

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PyVerse#4]
:red_circle: **Title** :Adding Workflows to Update Directory Structure in Real Time
:red_circle: **Aim** : Add Github action Workflows to Update Directory Structure in Real Time
:red_circle: **Brief Explanation** :

### Screenshots 📷

To update this section in real time when there is a change.
![image](https://github.com/user-attachments/assets/96c9c8cf-52b0-4016-85cd-b6a8d2743d1d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : [Yash Kumar Saini](https://github.com/yashksaini-coder)
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

Contributor for WoB'24 
***********************************************************************

Please add labels and assign this issue to me. @UTSAVS26

**Comment by yashksaini-coder** [comment]
how come this is `level1` issue

**Comment by UTSAVS26** [comment]
> can i start working on it from tomorrow. currently on a trip so network problems. also how come this issue is also a `level1`

Yeah you can work on from tomorrow in it, and why this issue is `level1` because level1 mostly contains contribution related to documentation, adding workflows and so, but you are adding any sort of code then it can be counted in `level2`

**Comment by yashksaini-coder** [comment]
> > can i start working on it from tomorrow. currently on a trip so network problems. also how come this issue is also a `level1`
> 
> Yeah you can work on from tomorrow in it, and why this issue is `level1` because level1 mostly contains contribution related to documentation, adding workflows and so, but you are adding any sort of code then it can be counted in `level2`

so let's suppose i add javascript or additional python to this issue it will become level2

**Comment by yashksaini-coder** [comment]
okh now i got it.

**Comment by UTSAVS26** [comment]
> > > can i start working on it from tomorrow. currently on a trip so network problems. also how come this issue is also a `level1`
> > 
> > 
> > Yeah you can work on from tomorrow in it, and why this issue is `level1` because level1 mostly contains contribution related to documentation, adding workflows and so, but you are adding any sort of code then it can be counted in `level2`
> 
> so let's suppose i add javascript or additional python to this issue it will become `level2` ?

Depends on the level of code contributed like basic or intermediate or so

**Comment by yashksaini-coder** [comment]
@UTSAVS26 can you add `level2` label to this.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 can you add `level2` label to this.  

I will change level at the time of merging along with PR you will be making
