### ISSUE TITLE
📃: ChessGame implementation

### ISSUE THREAD

**Issue by ojhankit** [UTSAVS26/PyVerse#40]
:red_circle: Title : Chess Game Project

:red_circle: Aim : To create a fully functional chess game that allows users to play against each other or an AI, showcasing the principles of Object-Oriented Programming (OOP) in Python.

:red_circle: Brief Explanation :
This project implements a chess game where two players can compete against each other. The game follows standard chess rules, with each piece having unique movement capabilities. It will include features like turn-based play, check and checkmate conditions, and a user-friendly interface. The project aims to demonstrate the application of OOP concepts such as encapsulation, inheritance, and polymorphism through classes for the chessboard, pieces, players, and game logic.

Screenshots 📷
N/A

:white_check_mark: To be Mentioned while taking the issue :

Full name : Ankit Ojha
What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by ojhankit** [comment]
@TheChaoticor assign this to me..

**Comment by TheChaoticor** [comment]
Will it be under beginner projects?

**Comment by moudgalya1223** [comment]
can we work together @UTSAVS26  it is very intresting

**Comment by UTSAVS26** [comment]
> can we work together @UTSAVS26  it is very intresting

Connect with me over email, are you contributor or mentor?

**Comment by moudgalya1223** [comment]
hello @UTSAVS26  wanted to be acontributor can you please drop your mail ?

**Comment by AnujSaha0111** [comment]
Please assign it to me. I want to work on it..
