### ISSUE TITLE
Add more accessibility buttons on navbar.

### ISSUE THREAD

**Issue by Premkolte** [UTSAVS26/PyVerse#409]
### Title

Navbar Update

### Enhancement Aim

having more navigation button on navbar

### Changes

new button will be added

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Prem Kolte

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@Premkolte on the website you want to add navbar?

**Comment by Premkolte** [comment]
Yes.

**Comment by Premkolte** [comment]
> Yes.

That would add a good accessibility to user.

**Comment by UTSAVS26** [comment]
@Premkolte have you joined the discord server?

**Comment by Premkolte** [comment]
Nope, I'll join.
@UTSAVS26

**Comment by UTSAVS26** [comment]
> Nope, I'll join.
> @UTSAVS26 

I am closing this issue right now after discussion on discord then raise issue.
