### ISSUE TITLE
[Code Addition Request]: Add a video player beginner web project

### ISSUE THREAD

**Issue by priyanshuverma-dev** [UTSAVS26/PyVerse#410]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

A Custom Video Player for Beginners in Web Development.

### Full Name

Priyanshu Verma

### Participant Role

GSOC, GSOC-Extd, Hacktoberfest

**Comment by UTSAVS26** [comment]
@priyanshuverma-dev you are using python in this project or not?

**Comment by priyanshuverma-dev** [comment]
@UTSAVS26 
I am using simple raw html , js and css

**Comment by UTSAVS26** [comment]
> @UTSAVS26 
> I am using simple raw html , js and css

Sorry but this project not be acceptable in this repo based on the rules shared on discussion and also if any project has been merged before they are going to be removed if they don't have python used.
