### ISSUE TITLE
[Code Addition Request]: 

### ISSUE THREAD

**Issue by Rashigera** [UTSAVS26/PyVerse#419]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Addition of binary trees concept to check if a tree is balanced

### Full Name

Rashi geta

### Participant Role

Contributor

**Comment by UTSAVS26** [comment]
@Rashigera are you only contributor of GSSOC or not?

**Comment by Rashigera** [comment]
Yes i am
