### ISSUE TITLE
[Code Addition Request]: Add Greedy Algorithms

### ISSUE THREAD

**Issue by sindhuja184** [UTSAVS26/PyVerse#424]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/YadavAkhileshh/Alien-Invasion-Defense/pull/100

### Project Description

Greedy algorithms are a fundamental concept in computer science and optimization, renowned for their simplicity and efficiency in solving a variety of problems. This comprehensive guide will delve into the principles of greedy algorithms, explore their applications, and provide Python implementations of classic greedy algorithms to enhance your understanding and coding skills.

I would like to add Activity Selection Problem, Fractional KnapSack Problem, Huffman Coding, Dijstra's shortest Path Algorithm, Prim's Algorithm, Kruskal's algorithm, Job Sequencing.

I would like to contribute.

Thanks @UTSAVS26 

### Full Name

Sindhuja D

### Participant Role

GSSOC Contributor

**Comment by UTSAVS26** [comment]
@sindhuja184 have you checked the project before raising the issue? As the things you have listed is already been done.
