### ISSUE TITLE
[Code Addition Request]: Addition of Hashing Algorithm

### ISSUE THREAD

**Issue by sindhuja184** [UTSAVS26/PyVerse#425]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/pull/316

### Project Description

I would like to add the hashing data structure.

I am interested to work on it.

Thanks @UTSAVS26 

### Full Name

Sindhuja Didugu

### Participant Role

GSSOC contributor

**Comment by UTSAVS26** [comment]
@sindhuja184 you can only raise 1 issue at a time.
