### ISSUE TITLE
[Code Addition Request]: Addition of Greedy Algorithm concepts, patterns, and their related problems set

### ISSUE THREAD

**Issue by J-B-Mugundh** [UTSAVS26/PyVerse#435]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/339

### Project Description

Addition of Greedy Algorithm concepts, patterns and their related problems set

### Full Name

J B Mugundh

### Participant Role

GSSOC-EXTD

**Comment by UTSAVS26** [comment]
@J-B-Mugundh what greedy algorithms you are planning to add on as there are some in the repo itself, did you check them?

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh what greedy algorithms you are planning to add on as there are some in the repo itself, did you check them?

I didn't see them. Now, I've referred them and I'm left with adding Prim’s Algorithm, Kruskal’s Algorithm, Fractional Knapsack solutions and a section for their related problems.

**Comment by J-B-Mugundh** [comment]
@UTSAVS26 If it feels redundant, you may close this issue!
