### ISSUE TITLE
🧑‍💻: Create a sign up and login page

### ISSUE THREAD

**Issue by poorvikaa08** [UTSAVS26/PyVerse#448]
### Title

We need to implement the sign-up and sign-in functionality for the project. The pages should be user-friendly, secure, and integrated with the backend for authentication. Below are the key features and expectations:

### Enhancement Aim

Sign-Up Page:
* Create a form for new users to register with the following fields:
* Full Name
* Email Address
* Password (with validation for strong passwords)
* Confirm Password
* Include an error message for invalid input.
* Add a button to submit the form and redirect users to the sign-in page after successful registration.
* Provide a link: "Already have an account? Login" that redirects to the sign-in page.

Sign-In Page:
* Create a form for users to log in with the following fields:
* Email Address
* Password
* Include an error message for incorrect credentials.
*Add a button to submit the form and redirect users to the home page after successful login.
* Provide a link: "Don’t have an account? Sign up" that redirects to the sign-up page.

### Changes

Add login and get started button which redirects the page into signup and login page

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Poorvika K B

### Participant Role

contributor @ gssoc-ext and hacktoberfest

**Comment by poorvikaa08** [comment]
@UTSAVS26 
Assign this issue to me under gssoc-ext and hacktoberfest.
Thank you

**Comment by UTSAVS26** [comment]
@poorvikaa08 is this signup page and login page required in this repo?

**Comment by poorvikaa08** [comment]
You could allow users to sign up if they want to track their progress, while also enabling guest users to leave feedback or reviews on resources without needing an account. This would give flexibility and cater to different types of users.

**Comment by poorvikaa08** [comment]
If your intention is to allow visitors to access the content freely, then a sign-up or login page might not be necessary.

However, if you plan to add personalized features like progress tracking, then implementing a login or sign-up functionality could be useful.

**Comment by UTSAVS26** [comment]
> If your intention is to allow visitors to access the content freely, then a sign-up or login page might not be necessary.
> 
> However, if you plan to add personalized features like progress tracking, then implementing a login or sign-up functionality could be useful.

The idea is great but we don't have any dynamic website that needs it right now, as right now the website is static, but if you are planning to work on this feature you can wait or you can create a complete website for it.

**Comment by UTSAVS26** [comment]
And if you are creating a new website create a new issue and tag me with this issue number so that i can label it level3 but it needs to be upto the mark and if not then the level can lower down.

**Comment by poorvikaa08** [comment]
@UTSAVS26 
Which new website are you referring to?
