### ISSUE TITLE
[Code Addition Request]: Adding Pig Dice game with python

### ISSUE THREAD

**Issue by Saipradyumnagoud** [UTSAVS26/PyVerse#453]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Adding Pig Dice Game Developed using Python

### Full Name

Ch.Sai Pradyumna 

### Participant Role

Hactoberfest,Gssoc Extended

**Comment by Saipradyumnagoud** [comment]
@UTSAVS26 Please assign me the issue

**Comment by GauravPatil2515** [comment]
Hello @utsaav26,

I hope you’re doing well! I am eager to work on adding the Pig Dice Game developed using Python to the project. I believe this addition will enhance the overall offerings and engage users with a fun gameplay experience.

Could you please grant me access to start working on this? I’m excited to contribute and look forward to developing this game for the repository.

Thank you for considering my request!

Best,
Gaurav Patil
Contributor for GirlScript Summer of Code 2024

**Comment by UTSAVS26** [comment]
> Hello @utsaav26,
> 
> I hope you’re doing well! I am eager to work on adding the Pig Dice Game developed using Python to the project. I believe this addition will enhance the overall offerings and engage users with a fun gameplay experience.
> 
> Could you please grant me access to start working on this? I’m excited to contribute and look forward to developing this game for the repository.
> 
> Thank you for considering my request!
> 
> Best,
> Gaurav Patil
> Contributor for GirlScript Summer of Code 2024

Hi @GauravPatil2515 don't comment on everyone assigned issues, you can raise a new issue and contribute based on that. If you see any open issue labelled as `Up for Grabs` then you can comment and ask to assign you that issue.

**Comment by GauravPatil2515** [comment]
ok i already reaised some issues but anyone is not labeling or assigning 
@UTSAVS26

**Comment by UTSAVS26** [comment]
> ok i already reaised some issues but anyone is not labeling or assigning 
> @UTSAVS26 

Which issues?
