### ISSUE TITLE
[Code Addition Request]: Add Lowest common Ancestor poblem

### ISSUE THREAD

**Issue by haseebzaki-07** [UTSAVS26/PyVerse#456]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

I want to add Lowest Common Ancestor tree problem under the tree section of Algorithm_And_Data_Structures

### Full Name

Haseeb Zaki

### Participant Role

GSSOC

**Comment by GauravPatil2515** [comment]
Hello @HaseebZaki,

I hope you’re doing well! I am eager to work on adding the Lowest Common Ancestor tree problem under the tree section of Algorithm_And_Data_Structures. I believe I can provide a detailed solution based on the provided information.

Could you please grant me access to start working on this? I’m excited to contribute and look forward to adding this problem to the repository.

Thank you for considering my request!

Best,
Gaurav Patil
Contributor for GirlScript Summer of Code 2024
