### ISSUE TITLE
[Code Addition Request]: latest news update using python

### ISSUE THREAD

**Issue by rohan-cce** [UTSAVS26/PyVerse#461]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

NA

### Project Description

in our news feed, the problem is most of them have clickbaits and incomplete title information just to pull in views for the particular website,
so i will work on creating a python parser which will give the header information from reliable sources and if user is interested he can continue reading the article, else go to next headline and continue

### Full Name

J Rohan

### Participant Role

hacktoberfest

**Comment by rohan-cce** [comment]
please assign me this issue, i will start working on it

**Comment by UTSAVS26** [comment]
@rohan-cce you can raise 1 issue at a time and you can read the mode guidelines in the discussion pages
