### ISSUE TITLE
[Code Addition Request]: for the curious mind, what to do if you are bored, how about a python script that generated a random article for you to study

### ISSUE THREAD

**Issue by rohan-cce** [UTSAVS26/PyVerse#462]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

NA

### Project Description

consider this scenario,
you are bored, you have been going through the repeated youtube video or ott recommendations
now just to do something interesting, we will create a python program which helps in generating a random article 
if you are interested you can go ahead or proceed with upcoming ones

### Full Name

J Rohan

### Participant Role

hacktoberfest

**Comment by rohan-cce** [comment]
please assign me this issue, i will start working on it

**Comment by UTSAVS26** [comment]
@rohan-cce you can raise 1 issue at a time and you can read the mode guidelines in the discussion pages
