### ISSUE TITLE
[Code Addition Request]: wiki summariser

### ISSUE THREAD

**Issue by rohan-cce** [UTSAVS26/PyVerse#463]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

NA

### Project Description

have you been in a place, where you need to go through lengthy article, but you have very less time to go through, no issues this python script will help in summarizing the article

### Full Name

J Rohan

### Participant Role

Hacktoberfest

**Comment by UTSAVS26** [comment]
@rohan-cce you can raise 1 issue at a time and you can read the mode guidelines in the discussion pages
