### ISSUE TITLE
[Code Addition Request]: 2048 Web Gem

### ISSUE THREAD

**Issue by SiddarthaKarri** [UTSAVS26/PyVerse#478]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/477

### Project Description

Added 2048 Web Game

### Full Name

Siddartha Karri

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@SiddarthaKarri you raise PR first without creating issue and waiting for assign?

**Comment by SiddarthaKarri** [comment]
@UTSAVS26 i created issue #478 and my PR for the issue is #477 
so pls assign me and merge my PR

**Comment by SiddarthaKarri** [comment]
@UTSAVS26 i did PR first as when i am opening an issue, it asked me to provide the link for the PR

**Comment by UTSAVS26** [comment]
> @UTSAVS26 i did PR first as when i am opening an issue, it asked me to provide the link for the PR

Yes it asked because it's normal practice to raise issue first and when it is assigned to you then create a PR. For this mistake from your side, I am closing both of them without merging.

**Comment by SiddarthaKarri** [comment]
@UTSAVS26 can i open issue and again merge it to ressolve my mistake?

**Comment by UTSAVS26** [comment]
> @UTSAVS26 can i open issue and again merge it to ressolve my mistake?

Yes you need to wait until issue is assigned to you then only PR is accepted.
