### ISSUE TITLE
🧑‍💻: user feedback 

### ISSUE THREAD

**Issue by Anushaburnwal** [UTSAVS26/PyVerse#48]
:red_circle: **user feedback** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : ANUSHA BURNWAL

- What is your participant role? ( GSSoC-Extd)
![SS](https://github.com/user-attachments/assets/553e2ae2-3cf0-4fdf-be1e-4ed2ae2e092b)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@Anushaburnwal please explain what you gonna do in this issue, you have left everything blank like

>🔴 user feedback :
>🔴 Enhancement Aim :
>🔴 Changes :

**Comment by Anushaburnwal** [comment]
we should include one feedback column for user that will be visible to user as well as the owner so that the users can check whether this website is user friendly or not. 
whatever problem the user is facing if the user reaching us through mail about the particular problem then we should send an automatic generated email response so that the user gets assured that we are fixing the problem.
we must make a community section where every user will connected to each other whether they are beginner or masters in the particular course so that they can reach out and help each other.
if any user wants to reach us for any urgent problem and incase our agents are not available at that moment then if we have stored Faqs then the user will be guided to the next solution or the next level and this makes your website more professional and more user freindly

**Comment by UTSAVS26** [comment]
> Title : Improvement in Feedback section
> Changes : User Feedback 
>  Community Section
> Automated Email Response
> Add a FAQ
> 

Okie I am assigning this issue to you and tell me your mail id so that i can give you direct edit access of the website.

**Comment by Anushaburnwal** [comment]
anushaburnwal84@gmail.com

**Comment by UTSAVS26** [comment]
> anushaburnwal84@gmail.com

I have send toh access of the website don't share it with anyone else.

**Comment by UTSAVS26** [comment]
> done

Please raise a PR if you done adding it

**Comment by Anushaburnwal** [comment]
I haven't done yet I will do this soon
