### ISSUE TITLE
[Code Addition Request] :  Adding Ping pong game under web development

### ISSUE THREAD

**Issue by AbhijitMotekar99** [UTSAVS26/PyVerse#486]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/155

### Project Description

This Ping Pong Game project will be a simple web-based game developed using HTML, CSS, and JavaScript. The game will simulate the classic ping pong experience where two paddles on either side of the screen move to hit a ball back and forth. The game will include scoring, a reset button, and increasing difficulty as the game progresses.

### Key features:

- Two paddles controlled via keyboard input (e.g., arrow keys or 'W'/'S' for player movements).
- A ball that bounces between the two paddles and walls, increasing speed after every hit.
- Scoring system that tracks player scores.
- A game reset or restart option.

### Full Name

Abhijit Motekar

### Participant Role

`gssoc-ext` `hacktoberfest`

**Comment by UTSAVS26** [comment]
@AbhijitMotekar99 sorry but the projects that don't have python used will not be approved, and projects that are already been merged are under process of being removed.
