### ISSUE TITLE
[Code Addition Request] :  Addition of Archery Game.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [UTSAVS26/PyVerse#487]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/155

### Project Description

The Archery Game project will be a web-based game created using HTML, CSS, and JavaScript. The player will aim and shoot arrows at a target board, with points awarded based on accuracy. The difficulty will increase as the target moves or as the wind speed changes, making it a more challenging and engaging experience.

### Key features:

- 
- Bow and arrow controlled by mouse drag-and-drop or keyboard inputs.
- Target board with different scoring areas (bullseye, outer rings).
- Realistic arrow physics (taking into account angle, speed, and possibly wind direction).
- Difficulty progression, including faster-moving targets or wind effect.
- Score tracking and reset options.

### Full Name

Abhijit Motekar

### Participant Role

`Gssoc-ext`  `gssoc-extd`  `Hacktoberfest`

**Comment by UTSAVS26** [comment]
@AbhijitMotekar99 you
