### ISSUE TITLE
[Code Addition Request] :  Adding Sliding window algorithm.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [UTSAVS26/PyVerse#488]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/155

### Project Description

The Sliding Window Algorithm is an optimized technique used to solve problems involving arrays or lists, where a "window" of elements is maintained, and the window is moved across the array. The technique is particularly effective in reducing time complexity for problems that require repeated calculations over a subset of elements, such as finding the maximum sum of a subarray of fixed length or determining if a certain condition is met over a sliding window.

### Full Name

Abhijit Motekar

### Participant Role

`gssoc-ext` `gssoc-extd` `Hacktoberfest`

**Comment by UTSAVS26** [comment]
@AbhijitMotekar99 in this issue you are going to use python right?

**Comment by AbhijitMotekar99** [comment]
Yes using python
