### ISSUE TITLE
[Code Addition Request] : Adding SMS Spam Detection Analysis - NLP

### ISSUE THREAD

**Issue by AbhijitMotekar99** [UTSAVS26/PyVerse#489]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/155

### Project Description

The SMS Spam Detection Analysis is a machine learning project that uses Natural Language Processing (NLP) techniques to classify SMS messages as either spam or legitimate (ham). The system processes and analyzes the text content of SMS messages to identify patterns or keywords commonly associated with spam.

### Full Name

Abhijit Motekar

### Participant Role

`gssoc-ext` `Hactoberfest`

**Comment by UTSAVS26** [comment]
@AbhijitMotekar99 you can only raise 1 issue at a time and please read guidelines before raising issues on discussion page.
