### ISSUE TITLE
📃:Zomato Restaurant Clustering and Sentiment Analysis

### ISSUE THREAD

**Issue by arhaanarif** [UTSAVS26/PyVerse#49]
Title: Zomato Restaurant Clustering and Sentiment Analysis

 The problem statement for this project is to analyze and understand the restaurant industry in India by utilizing data from the Indian restaurant aggregator and food delivery start-up, Zomato. The project aims to gain insights into the sentiments of customer reviews, cluster Zomato restaurants into different segments, and analyze the data to make useful conclusions in the form of visualizations. The data analyzed includes information on cuisine, costing, and customer reviews. The project aims to assist customers in finding the best restaurant in their locality and aid the company in identifying areas for growth and improvement in the industry. Additionally, the project aims to use the data for sentiment analysis and identifying critics in the industry through the metadata of reviewers.

- Full name : Arhaan Arif
- open source contributor GSSOC'24 Ext and Hacktoberfest

**Comment by alo7lika** [comment]
assign me this project @UTSAVS26 .

**Comment by UTSAVS26** [comment]
> assign me this project @UTSAVS26 .

This project has already been assigned to @arhaanarif you can raise another issue.

**Comment by UTSAVS26** [comment]
@arhaanarif what's the update?

**Comment by arhaanarif** [comment]
hi @UTSAVS26  while cloning I am getting an error due to file name "error: invalid path 'Machine_Learning/Hand Game Controller/"A" Key Binding.png'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed."
can you help me out for that

**Comment by UTSAVS26** [comment]
@arhaanarif try to clone again we have resolved the error.

**Comment by arhaanarif** [comment]
@UTSAVS26 still getting the same error!

**Comment by UTSAVS26** [comment]
@arhaanarif try to refork the repo and then reclone it as i have asked some contributors they said they are able to clone it.
