### ISSUE TITLE
[Code Addition Request]: Bestselling Books Analysis

### ISSUE THREAD

**Issue by deepanshubaghel** [UTSAVS26/PyVerse#492]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#401 

### Project Description

This project analyzes a dataset of best-selling books to uncover trends and patterns in pricing, ratings, reviews, and genres. Exploratory Data Analysis (EDA) includes visualizations like histograms, scatter plots, and pair plots to better understand the relationship between different variables. The project also employs machine learning models (e.g., Random Forest, K-Nearest Neighbors, XGBoost, Logistic Regression) to classify books based on their features. The Random Forest model achieves the highest accuracy. Data is preprocessed using techniques such as label encoding and scaling, and model performance is evaluated using classification metrics.

### Full Name

Deepanshu Baghel

### Participant Role

gssoc-ext

**Comment by deepanshubaghel** [comment]
@UTSAVS26

**Comment by UTSAVS26** [comment]
@deepanshubaghel you can raise 1 issue at a time.
