### ISSUE TITLE
[Code Addition Request]: Web3 Based Todo list with Etherium, Solidity and React JS

### ISSUE THREAD

**Issue by J-B-Mugundh** [UTSAVS26/PyVerse#493]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/339

### Project Description

I couldn't see any projects added in blockchain development :( 

So, I want to start adding to this series with a Todo list with Etherium, Solidity and React JS

### Full Name

J B Mugundh

### Participant Role

GSSOC-EXTD

**Comment by UTSAVS26** [comment]
@J-B-Mugundh you are planning to use python in it or not?

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh you are planning to use python in it or not?

No.. it doesn't have python's usage

**Comment by UTSAVS26** [comment]
> > @J-B-Mugundh you are planning to use python in it or not?
> 
> No.. it doesn't have python's usage

So sorry i can't able to accept this issue as the repo is only related to python and the projects that don't have python integrated are under process of being removed.
