### ISSUE TITLE
[Code Addition Request]: Web3 Based Charity Portal

### ISSUE THREAD

**Issue by J-B-Mugundh** [UTSAVS26/PyVerse#494]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/339

### Project Description

There are no platforms that can be used by charities to ensure security while providing accessibility to maximum people. The biggest problem faced is transparency, where people can rightly exercise their Right To Information by asking for a record of expenditure by the charity. Even if such applications are available, they are inaccessible to smaller organisations with a good user interface for ease of access. So, I want to create a web3 app for charity donations with etherium metamask and node js

### Full Name

J B Mugundh

### Participant Role

GSSOC-EXTD

**Comment by UTSAVS26** [comment]
@J-B-Mugundh you can only raise 1 issue at a time and please read guidelines before raising issues on discussion page.
