### ISSUE TITLE
[Code Addition Request]: Avocado Price Prediction

### ISSUE THREAD

**Issue by deepanshubaghel** [UTSAVS26/PyVerse#496]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#401 

### Project Description

This project utilizes machine learning models, including Random Forest Regressor, Linear Regression, and Ridge Regression, to predict avocado prices based on various features from a dataset. The analysis includes data preprocessing, visualization, and model evaluation, achieving a high accuracy of 93.469% with the Random Forest model.

### Full Name

Deepanshu Baghel

### Participant Role

gssoc-ext

**Comment by deepanshubaghel** [comment]
@UTSAVS26

**Comment by UTSAVS26** [comment]
> @UTSAVS26 

You can raise 1 issue at a time.
