### ISSUE TITLE
[Code Addition Request]: Customer Segmentation

### ISSUE THREAD

**Issue by inkerton** [UTSAVS26/PyVerse#498]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#395 

## Customer Segmentation Project Description

This project aims to segment customers into distinct groups based on their characteristics using K-Means clustering.

### Data Exploration:

* **Data Acquisition:** Downloads the "Mall_Customers.csv" dataset from Kaggle using the configured Kaggle API.
* **Data Loading:** Reads the downloaded CSV file into a pandas DataFrame for further analysis.
* **Data Overview:** Provides a glimpse of the data using functions like:
    * `.head()`: Displays the first few rows of the data.
    * `.shape`: Shows the number of rows and columns in the data.
    * `.describe()`: Generates summary statistics for numerical columns.
    * `.dtypes`: Displays the data types of each column.
    * `.isnull().sum()`: Checks for missing values in the data.

### Data Visualization:

* **Histograms:** Creates histograms for Age, Annual Income, and Spending Score to visualize their distribution.
* **Count Plot:** Creates a count plot to explore the distribution of customers across genders (Male and Female).
* **Scatter Plots:** Creates scatter plots to explore the relationships between Age, Annual Income, and Spending Score. Additionally, separate scatter plots are created for each gender to identify potential differences.
* **Violin Plots & Swarmplots:** Creates violin plots and swarmplots to visualize the distribution of Age, Annual Income, and Spending Score across genders, highlighting potential differences in central tendency and spread.

### Customer Segmentation using K-Means Clustering:

**1. Segmentation based on Age and Spending Score**

* **Feature Selection:** Selects Age and Spending Score as features for customer segmentation.
* **The Elbow Method:** Implements the Elbow Method to determine the optimal number of clusters. This method involves calculating the inertia (sum of squared distances between data points and their assigned cluster centers) for different numbers of clusters. The optimal number of clusters is typically chosen at the "elbow" where the inertia starts to increase slowly.
* **K-Means Clustering:** Performs K-Means clustering with the chosen number of clusters (4 in this case) to group customers based on their Age and Spending Score.
* **Visualization:** Visualizes the resulting clusters using a scatter plot, where data points are colored based on their assigned cluster. Additionally, the centroids (cluster centers) are plotted to represent the average values of each cluster.

This project demonstrates a customer segmentation approach using K-Means clustering based on customer demographics and spending behavior. The insights gained from this segmentation can be used for targeted marketing campaigns, product recommendations, and loyalty programs.

### Full Name

Janvi / inkerton

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@inkerton you can only raise 1 issue at a time and please read guidelines before raising issues on discussion page.
