### ISSUE TITLE
[Code Addition Request]: Movie Review System

### ISSUE THREAD

**Issue by inkerton** [UTSAVS26/PyVerse#500]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#395 

## Movie Review Sentiment Analysis Project Description

This project builds a system to classify movie reviews as positive or negative based on their sentiment.

### Data Acquisition:

* **Kaggle API Configuration:** Sets up the Kaggle API for downloading the required dataset (word2vec-nlp-tutorial).
* **Dataset Download:** Downloads the dataset containing labeled movie reviews from Kaggle.
* **Data Unzipping:** Unzips the downloaded dataset.

### Libraries:

* **pandas:** Used for data manipulation and analysis.
* **TfidfVectorizer:** Extracts features from text data using TF-IDF (Term Frequency-Inverse Document Frequency).
* **LogisticRegression:** Implements the Logistic Regression algorithm for sentiment classification.

### Data Exploration:

* **Importing Data:** Reads the training and testing data sets into pandas DataFrames.
* **Data Overview:** Provides a glimpse of the data using functions like:
    * `.head()`: Displays the first few rows of the data.
    * `.shape`: Shows the number of rows and columns in the data.
    * `.info()`: Displays information about data types and missing values.
    * `.describe()`: Generates summary statistics for numerical columns (descriptive for categorical columns if any).
* **Data Cleaning:**
    * Checks for missing values.
    * Checks for duplicate rows.
    * Drops the unnecessary "id" column from both training and testing data.
    * Creates a separate DataFrame for submission.

### Feature Engineering:

* **Text Preprocessing:** Assumed to be minimal (stop words removal) based on the provided code. This might be a point for further exploration (e.g., stemming, lemmatization).
* **TF-IDF Vectorization:** Converts textual reviews into numerical feature vectors using TF-IDF, which considers both the frequency of a word within a document and its overall frequency across the entire corpus.

### Model Building:

* **Logistic Regression:** Trains a Logistic Regression model to classify the reviews as positive or negative based on the TF-IDF features.
* **Model Evaluation:** Evaluates the model's performance using:
    * Accuracy score
    * F1 score (provided code snippet suggests calculating F1 score but not accuracy)
    * Confusion matrix (provided code snippet suggests printing confusion matrix)

### Submission:

* Generates predictions for the unseen test data using the trained model.
* Creates a submission file with the predicted sentiment labels for the test reviews.

This project demonstrates a simple movie review sentiment analysis system using TF-IDF features and Logistic Regression classification. You can explore further improvements by trying different machine learning algorithms, feature engineering techniques, and text pre-processing methods. 

### Full Name

Janvi / inkerton

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@you can only raise 1 issue at a time and please read guidelines before raising issues on discussion page.
