### ISSUE TITLE
[Code Addition Request]: Tic-Tac-Toe

### ISSUE THREAD

**Issue by souvikpramanikgit** [UTSAVS26/PyVerse#502]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

This is a two-player Tic-Tac-Toe game. The game board is a 3x3 grid where players take turns placing 'X' or 'O' in an empty cell. The game checks for a win or tie.

### Full Name

Souvik Kumar Pramanik

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@souvikpramanikgit please check open issues and pr before raising new issue as tictactoe has already been implemented.
