### ISSUE TITLE
[Code Addition Request]: Bubble Shoot Game

### ISSUE THREAD

**Issue by souvikpramanikgit** [UTSAVS26/PyVerse#503]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

It's like a shooting game , you can shoot by using space and collect points.

### Full Name

Souvik Kumar Pramanik

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@souvikpramanikgit what tech stack you are planning to use?

**Comment by souvikpramanikgit** [comment]
only python
