### ISSUE TITLE
[Code Addition Request]: Text-based adventure

### ISSUE THREAD

**Issue by souvikpramanikgit** [UTSAVS26/PyVerse#504]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

A very simple text-based adventure game where the player makes choices to navigate through the game and try to reach the treasure.

### Full Name

Souvik Kumar Pramanik

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@souvikpramanikgit you can only raise 1 issue at a time and please read guidelines before raising issues on discussion page.
