### ISSUE TITLE
ADD Real-Time Multi-User Whiteboard Application.

### ISSUE THREAD

**Issue by shubhagarwal1** [UTSAVS26/PyVerse#505]
1. The application uses a client-server architecture with Python's socket programming (or WebSockets for a more advanced version) to manage real-time interactions.
2. Multiple users can join the same session and draw shapes, lines, or freehand on a shared canvas.
3. Updates are broadcast in real-time, so all connected users see the same drawing.

Please assign this to me

**Comment by UTSAVS26** [comment]
@shubhagarwal1 raise a new issue and fill all the details that are asked in that template. I am closing this one.
