### ISSUE TITLE
🧑‍💻: Dark mode

### ISSUE THREAD

**Issue by nidhi752** [UTSAVS26/PyVerse#508]
### Title

I wish there was a dark mode feature on the website to enhance the user experience. It would not only improve the overall aesthetics but also make browsing more comfortable, especially in low-light conditions. Dark mode could reduce eye strain and offer a modern, sleek look, making the interface more visually appealing and easier to navigate.

### Enhancement Aim

Implementing a dark mode feature would make prolonged usage much more comfortable, especially during nighttime or in dimly lit environments. It would help reduce eye strain, allowing us to focus on the content for longer periods without discomfort. Additionally, a well-designed dark mode would add a layer of elegance to the interface, creating a more modern and professional look that could improve both usability and overall user satisfaction.

### Changes

Here's a list of changes I would like to make to incorporate dark mode into the project:

1. Add a toggle switch to allow users to switch between light mode and dark mode.
2. Adjust the background colors to darker shades while maintaining readability.
3. Change text colors to lighter shades that contrast well with the dark background.
4. Modify the colors of interactive elements like buttons, links, and icons to ensure they stand out clearly in dark mode.
5. Ensure that images and graphics adapt to dark mode without losing their clarity or impact.
6. Update hover and active states for elements to complement the dark mode design.
7. Implement smooth transitions between light mode and dark mode to create a seamless user experience.
8. Test the dark mode across different devices and screen sizes to ensure consistency and responsiveness. 

These changes aim to enhance the visual appeal and usability of the project while maintaining a comfortable viewing experience in all lighting conditions.

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Nidhi Kuntal

### Participant Role

GSSoC ext, Hackoctoberfest

**Comment by UTSAVS26** [comment]
@nidhi752 sorry, but for now we don't have any website so it can't be possible to add this feature right now, we have just a static website using `Google Sites`.

**Comment by nidhi752** [comment]
I am talking about the static website only. We can still implement this feature tho

**Comment by UTSAVS26** [comment]
>  I am talking about the static website only. We can still implement this feature tho

Did you check that `Google Sites` have these feature?
