### ISSUE TITLE
[Code Addition Request]: Create an Advanced BMI Calculator using Python and Tkinter GUI

### ISSUE THREAD

**Issue by amanver45** [UTSAVS26/PyVerse#517]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

n/a

### Project Description

I want to create an advanced BMI (Body Mass Index) calculator as a Python project with a graphical user interface (GUI) using Tkinter. This project should allow users to input their weight and height in various units, calculate their BMI, and categorize the result (e.g., Underweight, Normal weight, Overweight, Obese). The tool should include additional features like age and gender-based recommendations for ideal weight, as well as a clean, user-friendly interface.

Key Features:

Input fields for weight (kg, lbs) and height (cm, feet & inches).
A BMI calculation button that displays the result with category information.
Optionally provide an ideal weight range based on age, gender, and height.
Clear and reset buttons to reset inputs and output fields.
Clean, responsive GUI design using Tkinter.

### Full Name

Aman

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@amanver45 you can only raise 1 issue at a time and please read guidelines before raising issues on discussion page.
