### ISSUE TITLE
[Code Addition Request]: 2048 Website Game

### ISSUE THREAD

**Issue by SiddarthaKarri** [UTSAVS26/PyVerse#519]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

2048 Web Game is an easy-to-play number puzzle game. Slide tiles on a 4x4 grid to combine numbers and try to reach the 2048 tile. When two tiles with the same number touch, they merge into one with double the value. The goal is to keep merging tiles and see how high you can go!

### Full Name

Siddartha Karri

### Participant Role

GSSOC and HacktoberFest

**Comment by SiddarthaKarri** [comment]
@UTSAVS26 please assign me, i will do  it with no mistakes

**Comment by UTSAVS26** [comment]
@SiddarthaKarri sorry, but this project is already been under review in PR.

**Comment by SiddarthaKarri** [comment]
@UTSAVS26 but there is no PR where 2048 Web game is published
I was the one who opened a PR. As i made a mistake , you closed it.
Please check it sir.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 but there is no PR where 2048 Web game is published
> I was the one who opened a PR. As i made a mistake , you closed it.
> Please check it sir.

So you need to close that PR yourself and inform me on discord if anything like this happens.
