### ISSUE TITLE
[Code Addition Request]: Dijkstra Algorithm Visualizer

### ISSUE THREAD

**Issue by AnanteshG** [UTSAVS26/PyVerse#531]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/ChiragAgg5k/cal-buddy/pull/8

### Project Description

This Python project provides a visual representation of Dijkstra's algorithm on a graph. It allows users to input the number of nodes, specify the nodes, input the edges with weights, and choose a starting node. The script then visualizes the shortest distances and paths from the chosen starting node using networkx and matplotlib.

### Full Name

Anantesh G

### Participant Role

GSSoC, Hacktoberfest

**Comment by AnanteshG** [comment]
@UTSAVS26 Kind request to add level2 label for this project. Reason being this is an advanced python project with visualization.
![IMG-20240123-WA0041.jpg](https://github.com/user-attachments/assets/def829e6-b0a8-4994-ae47-d12573ff17a3)

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Kind request to add level2 label for this project. Reason being this is an advanced python project with visualization.
> ![IMG-20240123-WA0041.jpg](https://github.com/user-attachments/assets/def829e6-b0a8-4994-ae47-d12573ff17a3)

I can only add level2 or above levels to those issues which are solving bugs or adding new feature in the existing codebase not just the code.

**Comment by AnanteshG** [comment]
Ok no problem!
