### ISSUE TITLE
[Code Addition Request]: Add Hangman game in python 

### ISSUE THREAD

**Issue by shubhagarwal1** [UTSAVS26/PyVerse#535]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#534 

### Project Description

This is a simple Hangman game implemented in Python using the Tkinter library. Players guess letters to uncover a hidden word before running out of attempts.

### Full Name

Shubh Agarwal

### Participant Role

GSSOC Contributor

**Comment by UTSAVS26** [comment]
@shubhagarwal1 there is already a Hangman Game in this repo, so what you are planning to addon on to that project?

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 there is already a Hangman Game in this repo, so what you are planning to addon on to that project?

i am planning to add a new version of the app, with updates

**Comment by UTSAVS26** [comment]
> > @shubhagarwal1 there is already a Hangman Game in this repo, so what you are planning to addon on to that project?
> 
> i am planning to add a new version of the app, with updates 

I am assigning this issue to you and label in under level2 as you said you will add features in the existing code but if you create a new project for this then I will update the level to level1.

**Comment by shubhagarwal1** [comment]
> > > @shubhagarwal1 there is already a Hangman Game in this repo, so what you are planning to addon on to that project?
> > 
> > 
> > i am planning to add a new version of the app, with updates
> 
> I am assigning this issue to you and label in under level2 as you said you will add features in the existing code but if you create a new project for this then I will update the level to level1.

i will make sure to add the new version of the game application.
