### ISSUE TITLE
[Code Addition Request]: ADD Rock-Paper-Scissors game python

### ISSUE THREAD

**Issue by shubhagarwal1** [UTSAVS26/PyVerse#536]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#534 

### Project Description

Create a simple Rock-Paper-Scissors game where players can compete against the computer.

### Full Name

Shubh Agarwal

### Participant Role

GSSOC Contributor

**Comment by UTSAVS26** [comment]
@shubhagarwal1 you can only raise 1 issue at a time.

**Comment by shubhagarwal1** [comment]
hey @UTSAVS26 can please open the isseu now, as i have to wait this long to get assigned
