### ISSUE TITLE
[Code Addition Request]: ADD Sudoku game python

### ISSUE THREAD

**Issue by shubhagarwal1** [UTSAVS26/PyVerse#537]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#536  Raised merged

### Project Description

Create a Sudoku game where players can fill a 9x9 grid with digits so that each column, row, and subgrid contain all digits from 1 to 9 without repetition.

### Full Name

Shubh Agarwal

### Participant Role

GSSOC Contributor

**Comment by shubhagarwal1** [comment]
hey @UTSAVS26 as you have not assigned any of the issues to me, as you have declined the prev raised issue also, may i know the reason why didn't you assigned this to me, you just closed this likewise, also there is not rule of not raising more then 1 issue in the repo, we just cannot raise the same issue.

**Comment by UTSAVS26** [comment]
> hey @UTSAVS26 as you have not assigned any of the issues to me, as you have declined the prev raised issue #536, #535  also, may i know the reason why didn't you assigned this to me, you just closed this likewise, also there is not rule of not raising more then 1 issue in the repo, we just cannot raise the same issue.

I have defined the rules and guidelines for contributors in the discussion page and in that I have clearly stated that one contributor can raise only 1 issue at a time.

**Comment by UTSAVS26** [comment]
And like you said for the issue #536 i have closed it same like this issue 
And for #535 I didn't close that issue and waiting for your response if you are adding new features or just a simple project.

**Comment by shubhagarwal1** [comment]
Hey @UTSAVS26 as it takes time to issue get to be assigned, and while that time i am ideal becuase of the assignment 
i assure you if you assign me there three i will make sure to complete them by tonight,
if possible please assign me with 
#536 , #537

**Comment by UTSAVS26** [comment]
> Hey @UTSAVS26 as it takes time for issue to assigned, and while that time i am ideal becuase of the assignment issue.
> i assure you if you assign me there three i will make sure to complete them by tonight,
> if possible please assign me with 
> #536 , #537
> Your repo is part of GSSOC and GSSOC have their guidelines setted,  Please dont set your own rules this would make, us contributors difficult in contribution, if possible please don't do that.

Can you share the GSSOC guidelines where it is written that contributors can raise multiple issues at a time?

**Comment by UTSAVS26** [comment]
> Hey @UTSAVS26 as it takes time for issue to assigned, and while that time i am ideal becuase of the assignment issue.
> i assure you if you assign me there three i will make sure to complete them by tonight,
> if possible please assign me with 
> #536 , #537
> Your repo is part of GSSOC and GSSOC have their guidelines setted,  Please don't set your own rules this would make us contributors difficult in contribution, if possible please don't do that.

And the main goal of open source program is that to learn something new not just put add codes and also to contribute quality not quantity to gain points only.

**Comment by shubhagarwal1** [comment]
> > Hey @UTSAVS26 as it takes time for issue to assigned, and while that time i am ideal becuase of the assignment issue.
> > i assure you if you assign me there three i will make sure to complete them by tonight,
> > if possible please assign me with
> > #536 , #537
> > Your repo is part of GSSOC and GSSOC have their guidelines setted,  Please don't set your own rules this would make us contributors difficult in contribution, if possible please don't do that.
> 
> And the main goal of open source program is that to learn something new not just put add codes and also to contribute quality not quantity to gain points only.

I understand your concern, will contribute accordingly here. Thankyou for the opportunity.

**Comment by UTSAVS26** [comment]
> > > Hey @UTSAVS26 as it takes time for issue to assigned, and while that time i am ideal becuase of the assignment issue.
> > > i assure you if you assign me there three i will make sure to complete them by tonight,
> > > if possible please assign me with
> > > #536 , #537
> > > Your repo is part of GSSOC and GSSOC have their guidelines setted,  Please don't set your own rules this would make us contributors difficult in contribution, if possible please don't do that.
> > 
> > And the main goal of open source program is that to learn something new not just put add codes and also to contribute quality not quantity to gain points only.
> 
> I understand your concern, will contribute accordingly here. Thankyou for the opportunity.

Sure, all the best for future contributions.
