### ISSUE TITLE
[Code Addition Request]: Dynamic Programming Basic Algos

### ISSUE THREAD

**Issue by NK-Works** [UTSAVS26/PyVerse#538]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

NA

### Project Description

I want to create basic DP dir for leanring DP topics of DSA...
I am thinking of making it a series of issue starting from basics all the way to pro level.

### Full Name

Anneshu Nag (NK-Works)

### Participant Role

GSSOC, Hacktoberfest

**Comment by UTSAVS26** [comment]
@NK-Works list few algos you are planning to addon.

**Comment by NK-Works** [comment]
my plan is to divide the dynamic problems into 9 parts...
3 easy, 3 medium and 3 hard
for the easy part..
1. fibonacci seq algo
2. Climbing stairs algo 
3. house robber algo (this issue)

will raise 2 or 3 more issues for the the others.
