### ISSUE TITLE
[Code Addition Request]: Bellmon Ford Algo

### ISSUE THREAD

**Issue by NK-Works** [UTSAVS26/PyVerse#539]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

NA

### Project Description

Add the bellmon ford algorithm

### Full Name

Anneshu Nag (NK-Works)

### Participant Role

GSSOC, Hacktoberfest

**Comment by UTSAVS26** [comment]
@NK-Works you can only raise 1 issue at a time.
