### ISSUE TITLE
[Code Addition Request]: Crypto Tracker project in react with animations and charts showing 3-4 months data

### ISSUE THREAD

**Issue by devxMani** [UTSAVS26/PyVerse#541]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Crypto Tracker project in react with animations and charts showing 3-4 months data

### Full Name

Mani

### Participant Role

GSSOC ext

**Comment by UTSAVS26** [comment]
@devxMani your project uses python or not?

**Comment by devxMani** [comment]
@UTSAVS26 yes uses python

**Comment by devxMani** [comment]
@UTSAVS26 can you add level 2

**Comment by UTSAVS26** [comment]
> @UTSAVS26 can you add level 2

Level 2 and 3 are for only bug fixing or new feature that is being adding in the existing codebase not for projects. Sorry for that.

**Comment by devxMani** [comment]
@UTSAVS26 ok thanks bro for clearing doubt

**Comment by UTSAVS26** [comment]
> @UTSAVS26 ok thanks bro for clearing doubt

You are welcome bro.
