### ISSUE TITLE
[Code Addition Request]: Adding a 2048 Game in Game Development

### ISSUE THREAD

**Issue by Kritika75** [UTSAVS26/PyVerse#549]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/suryanshsk/Python-Voice-Assistant-Suryanshsk/pull/170#event-14615961353

### Project Description

Implementing the popular sliding puzzle game where players combine tiles with the same number to create larger tiles, aiming to reach the 2048 tile.

### Full Name

Kritika Singh

### Participant Role

Contributor at Gssoc'24 ext

@UTSAVS26 can you assign me this?

**Comment by UTSAVS26** [comment]
@Kritika75 there is already a PR on this game

**Comment by Kritika75** [comment]
> @Kritika75 there is already a PR on this game

Oh, sorry! I think I missed that
