### ISSUE TITLE
🧑‍💻: Addition of All Contributors in Readme.md file

### ISSUE THREAD

**Issue by Rahul-AkaVector** [UTSAVS26/PyVerse#552]
### Title

**Addition of All Contributors in Readme.md file**

### Enhancement Aim

The aim of this enhancement is to acknowledge the contributions of all individuals who have contributed to the project by adding a "Contributors" section in the `README.md` file. This will serve as a token of appreciation for their efforts.

### Changes

- Add a **Contributors** section to the `README.md` file.  
- Include contributor names, roles, and profile links using the [All Contributors](https://allcontributors.org/docs/en/bot/usage) specification or manual listing.  
- Ensure the design and layout of the section are consistent with the current `README.md` style.

Like this..

### Screenshots 📷

![image](https://github.com/user-attachments/assets/a87aa4b2-c518-41bc-b0b3-2bd8aec7cee8)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Rahul-AkaVector

### Participant Role

GSSOC, HACKTOBERFEST,

**Comment by UTSAVS26** [comment]
@Rahul-AkaVector this issue has already been taken care in one of the open assigned issues.
