### ISSUE TITLE
[Code Addition Request]: Visual Novel code

### ISSUE THREAD

**Issue by Chin-may02** [UTSAVS26/PyVerse#556]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/issues/332

### Project Description

This is an interactive visual base novel game that works on user choice. It will have multiple scenarios for each choice of option.

### Full Name

Vuppu Chinmay

### Participant Role

gssoc-ext and hacktoberfest

**Comment by UTSAVS26** [comment]
@Chin-may02 you are going to use Python in this project?

**Comment by Chin-may02** [comment]
Yes, but I might import a few libraries.
I will mention them in the readme file.
I not possible I will let you know if I shift to another language.

**Comment by UTSAVS26** [comment]
> Yes, but I might import a few libraries.
> I will mention them in the readme file.
> If not possible I will let you know if I shift to another language if you permit to do so.
>  
> 

I will accept this project if you use python, i will check it in the PR you raised.

**Comment by Chin-may02** [comment]
Okay will limit it to python.
