### ISSUE TITLE
[Code Addition Request]:Tutorials

### ISSUE THREAD

**Issue by ojhankit** [UTSAVS26/PyVerse#564]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/368

### Project Description

I want to contribute to the tutorial section of the repository by adding code examples and explanations for fundamental data structures such as lists, sets, tuples, and dictionaries, along with tutorials on methods, file handling, and more. This will help enhance the repository with valuable learning resources for new users.

### Full Name

Ankit Ojha

### Participant Role

Contributor GSSOC - EXT

**Comment by UTSAVS26** [comment]
@ojhankit work on 1 issue at a time, you can reopen it after completing the previous one and tag me to assign you.
