### ISSUE TITLE
📃: Graphs

### ISSUE THREAD

**Issue by South-IN** [UTSAVS26/PyVerse#57]
:red_circle: **Title** : Graphs for DSA
:red_circle: **Aim** : Add the graph data structure implementation.
:red_circle: **Brief Explanation** :Graphs represent relationships between entities using vertices and edges. They are implemented using adjacency lists or matrices and are vital for solving problems like searching (BFS, DFS) and finding the shortest path (Dijkstra’s). I plan to implement a Menu driven Graph implementation that will include a shortest distance calculator and graph traversal methods.

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Saurav Singh.
- Participant role : Contributor in Hactoberfest.

**Comment by South-IN** [comment]
i want to work on this issue /assign me.

**Comment by South-IN** [comment]
@UTSAVS26 yes

**Comment by South-IN** [comment]
@UTSAVS26 Can i work on the issue ?

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Can i work on the issue ?
> 

As of now I don't know if this project is allowed under Hacktoberfest or not so if you don't have a problem with it, i can assign you this issue.

**Comment by South-IN** [comment]
No problem assign this issue to me under hacktoberfest tag please.

**Comment by South-IN** [comment]
@AnujSaha0111 I am already assigned to this issue.

**Comment by Navyachinta** [comment]
Hello @UTSAVS26. I have good knowledge in DSA and Graphs. I would like to work on this. Could you please assign this to me.

**Comment by UTSAVS26** [comment]
> Hello @UTSAVS26 @South-IN . I have good knowledge in DSA and Graphs. I would like to work on this. Could you please assign this to me.

Raise another issue if possible I am closing this one.
