### ISSUE TITLE
[Code Addition Request]: Voting Project in Blockchain Development

### ISSUE THREAD

**Issue by ShivRaiGithub** [UTSAVS26/PyVerse#576]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/vigneshs-dev/Q-Vote/pull/21

### Project Description

I would like to add a simple Voting DApp in Blockchain development. It will allow users to vote for the candidates. It will be a decentralized and secure voting.

### Full Name

Shiv Shakti Rai

### Participant Role

GSSOC EXT

**Comment by UTSAVS26** [comment]
@ShivRaiGithub what tech stack you are using in this project?

**Comment by ShivRaiGithub** [comment]
@UTSAVS26 For the contracts, Foundry since it is faster than Hardhat and also because we won't be using js. Web3.py for connecting frontend to backend. For the frontend, Flask.
