### ISSUE TITLE
📃: Add Beginner-Level Python Projects

### ISSUE THREAD

**Issue by PasamTharun** [UTSAVS26/PyVerse#58]
:red_circle: **Title** :Add Beginner-Level Python Projects
:red_circle: **Aim** :To provide beginner-friendly Python projects that help learners practice basic Python programming skills.
:red_circle: **Brief Explanation** :I would like to contribute a set of beginner-level Python projects aimed at enhancing the foundational understanding of core Python concepts. These projects focus on practical applications involving user inputs, date and time functions, and simple interactive features. They will serve as excellent practice exercises for new learners to improve their coding skills and confidence in Python programming.

### Screenshots 📷
N/A 

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pasam Tharun
- Contributor(GirlScript Summer of Code (GSSOC) 2024 - Extended Edition)

**Comment by PasamTharun** [comment]
👋 Hey @UTSAVS26,

I really admire the work you're doing on this project and would love the opportunity to contribute! 🚀 I'm particularly interested in working on Beginner Projects, and I have experience with relevant skills/technologies that I believe can add value.

Could you kindly assign this issue to me? I’m excited to dive in and collaborate with you to make this even better! 😄

Looking forward to hearing from you and getting started!

**Comment by UTSAVS26** [comment]
@PasamTharun what is this? You closed the issue?

**Comment by PasamTharun** [comment]
@UTSAVS26 
Very sorry For closing the issue It was happened Unfortunately

**Comment by PasamTharun** [comment]
@UTSAVS26  Please Assign it to me i Would like to contribute on this!

**Comment by UTSAVS26** [comment]
@PasamTharun you only maid the PR for the file onto your cloned repo not in the main repo.
