### ISSUE TITLE
[Code Addition Request]: Add Weather App to Beginner_Projects

### ISSUE THREAD

**Issue by psanyalaich** [UTSAVS26/PyVerse#589]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Want to build a simple weather app using python and API

### Full Name

Prisha Sanyal Aich

### Participant Role

`gssoc-ext`, `hacktoberfest-accepted`

**Comment by UTSAVS26** [comment]
@psanyalaich what tech stack you are planning to use?

**Comment by psanyalaich** [comment]
I'm planning to use Python, PyQt5, and OpenWeather API
