### ISSUE TITLE
Missing docker-compose.yml File for Backend Setup

### ISSUE THREAD

**Issue by Sachin2815** [UTSAVS26/PyVerse#595]
Hey! @UTSAVS26 

I noticed that the repository does not contain a `docker-compose.yml` file, which is essential for streamlining the setup of the backend services, particularly for the PostgreSQL database integration.

I have extensive experience in setting up Docker environments for both local development and production use. I've worked on several projects where `docker-compose` played a crucial role in streamlining the development process, and I am confident that I can deliver a high-quality solution for this repository.

The addition of a `docker-compose.yml` file would greatly improve the development and deployment process by enabling easier orchestration of the backend services using Docker. It can help set up both the Axum-based Rust backend and the PostgreSQL database seamlessly.

## Proposed Solution

I would like to contribute by adding a `docker-compose.yml` file that:

- Defines services for the backend and PostgreSQL.
- Configures networking to allow smooth communication between the backend and the database.
- Includes relevant environment variables for database setup (e.g., username, password, database name).

This will allow contributors and developers to quickly spin up the backend environment using Docker, enhancing productivity and minimizing setup errors.

Please let me know if this sounds like a good enhancement, and I'd be happy to get started! 😊

Thank you for your consideration!

**Comment by UTSAVS26** [comment]
@Sachin2815 what is your contribution role?

**Comment by Sachin2815** [comment]
Hi @UTSAVS26 ,

Thanks for asking! 

I'm currently contributing as part of **Hacktoberfest** and **GSSoC Extended**, where I'm actively looking to collaborate on open-source projects like yours. My main focus is on improving infrastructure setups using Docker, PostgreSQL, and ORM solutions like Prisma, while also assisting with backend transitions if required. 

I'm really excited to contribute to this project and help streamline the development process with the solutions we've discussed!

Looking forward to your thoughts 😊
