### ISSUE TITLE
🐛:  Auto Comment on PR Merge and Issue Close Failing Due to Errors

### ISSUE THREAD

**Issue by UTSAVS26** [UTSAVS26/PyVerse#6]
:red_circle: **Title** :  
Auto Comment on PR Merge and Issue Close Failing Due to Errors

:red_circle: **Bug** :  
1. **PR Merge Auto Comment Fails:**  
   When attempting to auto-comment on PR merge, the following error occurs:
   ```json
   {
     "message": "Resource not accessible by integration",
     "documentation_url": "https://docs.github.com/rest/issues/comments#create-an-issue-comment",
     "status": "403"
   }
   Error: Process completed with exit code 1.
   ```

2. **Issue Close Auto Comment Fails:**  
   The following syntax error is preventing the auto-comment from being added on issue close:
   ```bash
   /home/runner/work/_temp/00cb0ad8-b57c-4b74-9eca-ec7eaf8b5b70.sh: line 18: syntax error: unexpected end of file
   Error: Process completed with exit code 2.
   ```

:red_circle: **Changes** :  
- **Fix the PR Merge Comment Issue:**
  - Investigate and resolve the "Resource not accessible by integration" error (HTTP 403). Likely permissions issue with the integration or missing access token.
- **Fix the Syntax Error on Issue Close:**  
  - Check the shell script responsible for closing the issue and correct the syntax, specifically at line 18 where the error arises from an unexpected EOF.

**********************************************************************

**Comment by yashksaini-coder** [comment]
> can you assign this issue to me @UTSAVS26 I would like to try and resolve the error

hi @UTSAVS26 assign this issue to me and add labels to it.

**Comment by UTSAVS26** [comment]
> > can you assign this issue to me @UTSAVS26 I would like to try and resolve the error
> 
> hi @UTSAVS26 assign this issue to me and add labels to it.

Sure

**Comment by yashksaini-coder** [comment]
> > > can you assign this issue to me @UTSAVS26 I would like to try and resolve the error
> > 
> > 
> > hi @UTSAVS26 assign this issue to me and add labels to it.
> 
> Sure

Thanks 👍🏼 @UTSAVS26
