### ISSUE TITLE
🧑‍💻: Testimonials Section

### ISSUE THREAD

**Issue by devxMani** [UTSAVS26/PyVerse#612]
### Title

Creating new testimonials

### Enhancement Aim

testimonials

### Changes

N/A

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Mani

### Participant Role

GSSOC ext 24

**Comment by UTSAVS26** [comment]
@devxMani you can only raise 1 issue at a time.
