### ISSUE TITLE
🧑‍💻: Enhancement of Navbar adding sections ( Home , about , FAQs )

### ISSUE THREAD

**Issue by devxMani** [UTSAVS26/PyVerse#613]
### Title

Enhancement of Navbar 

### Enhancement Aim

Navbar

### Changes

N/A

### Screenshots 📷

![image](https://github.com/user-attachments/assets/56d7fc4c-1699-4436-8c5a-7f63b5efddc6)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Mani

### Participant Role

GSSOC ext 24

**Comment by UTSAVS26** [comment]
Raise 1 issue at a time.
