### ISSUE TITLE
🧑‍💻:  Add Most Important Project for Today's era 

### ISSUE THREAD

**Issue by SimranShaikh20** [UTSAVS26/PyVerse#615]
### Title

Project must be there 
Machine_Learning

Hi, I am Simran Shaikh. I’ve been reviewing the project as part of my contribution to GSSoC Extended 24 and noticed that there must be project of credit card fruad detection as i has increasing too much .
 I would like to work on this.
If you like this idea, assign the task to me and add the corresponding charts to it.
Thank you for your time and consideration!

### Enhancement Aim

To find fraud transaction .

### Changes

Adding project to machine learning section.

### Screenshots 📷
@UTSAVS26 
if you assign me work i will work on it.

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

@SimranShaikh20

### Participant Role

GSSOC ectended 2024

**Comment by UTSAVS26** [comment]
And the level can't be changed as you are just adding project not something related to buy fixing or new feature in existing codebase.

**Comment by SimranShaikh20** [comment]
> And the level can't be changed as you are just adding project not something related to buy fixing or new feature in existing codebase.

Yes your are right but i had added 1 entire project based on real life problem that's why and added function like data cleaning , data analysing  and machine leraning .
