### ISSUE TITLE
📃: Add Fake News Detection using NLP

### ISSUE THREAD

**Issue by pavitraag** [UTSAVS26/PyVerse#63]
:red_circle: **Title** : Fake News Detection
:red_circle: **Aim** : To detect Fake news 
:red_circle: **Brief Explanation** : This project is a Fake News Detection system using NLP and Logistic regression to make the prediction, on whether the news is fake or not.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Pavitraa G
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
Gssoc Extd Contributor, Hacktoberfest Contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Teja-m9** [comment]
Hey please assign this task to me and i have some experience in doing these projects

**Comment by UTSAVS26** [comment]
> Hey please assign this task to me and i have some experience in doing these projects
> 

Sorry but this project as already been assigned you can raise another issue with some different project.
