### ISSUE TITLE
[Code Addition Request]: Perceptron Learning Algorithm

### ISSUE THREAD

**Issue by Suvadip-sana** [UTSAVS26/PyVerse#631]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Perceptron learning algorithm using Diabeties Data set. Implement of both AND & OR function.

### Full Name

Suvadip Sana

### Participant Role

**gssoc-extd, hacktoberfest-accepted**

**Comment by UTSAVS26** [comment]
@Suvadip-sana raise 1 issue at a time.
