### ISSUE TITLE
[Code Addition Request]: Bit plane slicing using OPEN CV & Matplot Lib

### ISSUE THREAD

**Issue by Suvadip-sana** [UTSAVS26/PyVerse#633]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Bit plane slicing using opencv and matplotlib.    It's slice the image of it's 8 bit
![image](https://github.com/user-attachments/assets/a48b86c1-438e-4642-83ef-365a7054f03f)

### Full Name

Suvadip Sana

### Participant Role

**gssoc-extd, hacktoberfest-accepted**

**Comment by UTSAVS26** [comment]
@Suvadip-sana raise 1 issue at a time.

**Comment by Suvadip-sana** [comment]
@UTSAVS26 Is this a restriction? 
If yes. Then sorry. It was unintentionally.

**Comment by Suvadip-sana** [comment]
@UTSAVS26 
I create a PR #667   for the ISSUE #630 

Now please assign me this ISSUE. I want to contribute this in `Image processing` field.
