### ISSUE TITLE
[Code Addition Request]: Steganography using Open Cv & Matplot lib

### ISSUE THREAD

**Issue by Suvadip-sana** [UTSAVS26/PyVerse#634]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Hidding one secret image inside a image. Embedding secret image to two lsb of cover image.

It's has also MSE, PSNR statistical analysis of the output for understanding the correctness of the model.
![image](https://github.com/user-attachments/assets/ae21b37d-157d-4238-aa55-74fff34ac1ce)
![image](https://github.com/user-attachments/assets/ef015817-13b7-4dcb-8049-f7e875587109)
![image](https://github.com/user-attachments/assets/6ce85922-33bc-4d95-887c-481a789aabc9)

### Full Name

Suvadip Sana

### Participant Role

**gssoc-extd, hacktoberfest-accepted**

**Comment by UTSAVS26** [comment]
@Suvadip-sana raise 1 issue at a time.
