### ISSUE TITLE
[Code Addition Request]: Want to add new Web development project that is 'Currency Converter'

### ISSUE THREAD

**Issue by Suvadip-sana** [UTSAVS26/PyVerse#637]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

I wan to add the 'Currency Converter' web application that use HTML, CSS, Java Script  Currency Converter API, Flag API.
It support more than 150 country currency.
Here is the demo-
![currency1](https://github.com/user-attachments/assets/4a54c82c-cda1-4a8a-a491-ecb276aab9e8)

### Full Name

Suvadip Sana

### Participant Role

`gssoc-extd`, `hacktoberfest-accepted`

**Comment by UTSAVS26** [comment]
@Suvadip-sana raise 1 issue at a time.
