### ISSUE TITLE
🧑‍💻: Adding Hovering effect in Directory Hub

### ISSUE THREAD

**Issue by Ashish-Patnaik** [UTSAVS26/PyVerse#647]
### Title

It looks better and give a better user expierence 

### Enhancement Aim

A beautiful looking UI

### Changes

Hovering in the Directory Hub

### Screenshots 📷

NA

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Ashish Patnaik

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@Ashish-Patnaik can you provide some screenshots what are you gonna do in hovering UI?

**Comment by Ashish-Patnaik** [comment]
I can't provide screenshots as I did not not work on your project but I worked on other website where I made these types of effect I will provide a video of a attractive card animation that I made  

https://github.com/user-attachments/assets/ac8e2257-6261-4a1c-9da3-d2fcb2730a87

https://github.com/user-attachments/assets/2fcfe149-7f56-451c-ba06-2a0cf6b8e18b

**Comment by UTSAVS26** [comment]
@Ashish-Patnaik the thing is there is no proper website for the project as the website is being created using `Google Sites` and it doesn't provide much customization. 

If you want to create a new website from scratch you can raise a new issue I will assign it to you with higher levels, if you want to.
