### ISSUE TITLE
Footer and Navigation Bar is to be added to the website

### ISSUE THREAD

**Issue by Ashwinib26** [UTSAVS26/PyVerse#65]
Navigation Bar:
A fixed navigation bar at the top of the website would provide users with quick access to important sections such as "Home," "Projects," "Blog," "About," "Contact," and any other relevant links.
This will improve usability by allowing users to navigate between pages seamlessly without scrolling or searching, making the site more intuitive and user-friendly.

Footer:
A footer at the bottom of each page could include key information such as "Terms and Conditions," "Privacy Policy," "Contact Details," and "Site Map."
Social media icons for GitHub, LinkedIn, and other relevant platforms can be added, alongside a newsletter subscription option or quick links to blog posts or projects.

**Comment by anurag-in05** [comment]
I want to fix this issue. Please assign this to me.

**Comment by UTSAVS26** [comment]
@Ashwinib26 please use dedicated templates to raise an issue. It will help maintainers to look and assigning. I am closing this issue. All the best. 
And I have already assigned you one issue so work on that.

And @anurag-in05 if you want to work on this issue, raise a new issue with proper template. All the best.
