### ISSUE TITLE
🧑‍💻: Improve the turtle code 

### ISSUE THREAD

**Issue by Chin-may02** [UTSAVS26/PyVerse#66]
Following improvement can be done in the turtle code in the beginners projects 
1. User specific angle for the turtle to turn
2. If color not specified using default color
 Could you please assign me this issue I would like to work on it, do add the labels of gssoc-ext, hacktoberfest and hacktoberfest-accepted

**Comment by Chin-may02** [comment]
I want to make these right Could you please assign this to me with the labels of gssoc-ext, hacktoberfest and hacktoberfest-accepted

**Comment by UTSAVS26** [comment]
@Chin-may02 please use dedicated templates to raise an issue. It will help maintainers to look and assigning. I am closing this issue. All the best.
