### ISSUE TITLE
🧑‍💻: Improve the QR Generator code

### ISSUE THREAD

**Issue by djv554** [UTSAVS26/PyVerse#67]
Hi,

I can make some changes in the QR Generator Code in the Beginner_Projects folder by adding additional features and improving overall structure. Following improvements can be done:
1)Add User Input: Allow dynamic input for the URL, colors, and file name.
2)Add Error Handling: Check if the URL is valid or handle potential issues.
3)Make Reusable Functions: Modularize the script for better readability and reusability.

Please assign this issue to me.
Also please add the gssoc-ext and hacktoberfest-accepted labels.

**Comment by UTSAVS26** [comment]
@djv554 please use dedicated templates to raise an issue. It will help maintainers to look and assigning. I am closing this issue. All the best.
