### ISSUE TITLE
🧑‍💻:  Add Deployment link 

### ISSUE THREAD

**Issue by harshpardeshi09** [UTSAVS26/PyVerse#694]
### Title

to add Deployment link in readme.md file

### Enhancement Aim

adding deployment link in readme.md will make others easier to view the preview of project

### Changes

I will make changes in readme.md file. I will deploy the link in project's title name 

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Harsh Santosh Pardeshi

### Participant Role

gssoc, hacktoberfest, gssoc-extd

**Comment by harshpardeshi09** [comment]
@UTSAVS26 assign me with this issue and give necessary labels

**Comment by UTSAVS26** [comment]
@harshpardeshi09 sorry, but I don't think it is necessary.
