### ISSUE TITLE
🐛: No Blockchain project

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PyVerse#696]
### Title

No Blockchain implementation

### Bug

There is not a single blockchain implementation using python programming language. No simple project or script is found in the blockchain project.

### Changes

I would like to create a simple flask implementation using blockchain development and some beginner level concepts in hard coding approach. This will make the application directly embedding into the source code of the project

### Full Name

[Yash Kumar Saini](https://github.com/yashksaini-coder)

### Participant Role

GSSOC-Ext

**Comment by yashksaini-coder** [comment]
@UTSAVS26 check this issue & assign it to me with proper labels

**Comment by UTSAVS26** [comment]
@yashksaini-coder what tech stack you are planning to utilise?

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder what tech stack you are planning to utilise?

hi @UTSAVS26 

- **Flask (Python)**: Backend framework to create API routes for blockchain operations (e.g., `/mine`, `/chain`).
- **Hashlib**: Generates cryptographic hashes to secure blocks in the blockchain.
- **ECDSA**: Creates public/private key pairs for user wallets and signs transactions.
- **SQLite**: Stores the blockchain, transactions, and user data persistently.
- **JSON Serialization**: Converts blockchain data into JSON for API responses.
- **HTML/CSS/JavaScript**: Optional frontend to display blockchain data.
- **Heroku/Docker**: Deploys the Flask app to the web or containerizes it for consistent environments.
- **Flask-JWT**: Adds security through user authentication and API protection.


well main important ones are the above mentioned for a full stack blockchain project

My approach is a light weight way to just create wallets and mine blocks and use json-serilization, with HTML, CSS, Javascript for frontend & flask for backend

**Comment by yashksaini-coder** [comment]
@UTSAVS26 I have raised a PR for this issue fix #792 and I think this could be level 3
