### ISSUE TITLE
Enhance the look and feel of the cards on the homepage 

### ISSUE THREAD

**Issue by shubhagarwal1** [UTSAVS26/PyVerse#699]
I propose to add hover effects and make the cards more appealing 
<img width="745" alt="Screenshot 2024-10-18 at 4 21 22 PM" src="https://github.com/user-attachments/assets/65226043-ec66-4204-8745-8051528e21fa">

**Comment by UTSAVS26** [comment]
Where and how? As there is no coded website for this project.
