### ISSUE TITLE
📃: Linked Lists

### ISSUE THREAD

**Issue by aviralgarg05** [UTSAVS26/PyVerse#7]
:red_circle: **Title** : Linked Lists
:red_circle: **Aim** : DSA Linked Lists Exampls
:red_circle: **Brief Explanation** :Linked lists are a fundamental data structure that allows efficient storage and manipulation of data

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aviral Garg
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC 24' Extended

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@aviralgarg05 please raise one issue at a time. I am only assigning this issue to you and wait for others if any other contributor wants to work on it then I will assign it to them otherwise when you are done with this issue you can comment on them to assign yourself those issues.
