### ISSUE TITLE
🧑‍💻: Add a "Back to Top" button

### ISSUE THREAD

**Issue by banasmita24** [UTSAVS26/PyVerse#702]
### Title

To improve user navigation by adding a "Back to Top" button on all pages, which will enhance user experience and provide smoother scrolling through content.

### Enhancement Aim

The goal is to enhance the user interface by adding a "Back to Top" button that improves navigation for users on long pages. This feature allows users to quickly scroll back to the top without manually scrolling, making the website more user-friendly and efficient.

### Changes

- Implement a floating "Back to Top" button that appears after the user scrolls down a certain distance.
- Add smooth scrolling behavior to ensure a seamless experience when the button is clicked.
- Make the button visible only when the user scrolls down, and hide it when the user is at the top of the page.
- Ensure the button's styling is consistent with the project's design, using appropriate colors, fonts, and animations.
- Test the button for responsiveness on various screen sizes and devices to ensure cross-platform compatibility.

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Banasmita Jena

### Participant Role

GSSOC-extd, hacktoberfest-accepted

**Comment by UTSAVS26** [comment]
@banasmita24 where are you planning to add the button?

**Comment by banasmita24** [comment]
@UTSAVS26 I am planning to add it in the right bottom corner of the page.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 I am planning to add it in the right bottom corner of the page.

On website?

**Comment by banasmita24** [comment]
Yes

**Comment by UTSAVS26** [comment]
There is no coded website for the project right now.
