### ISSUE TITLE
I want to add "Retrieval-Augmented Generation using Langchain" under Generative AI folder

### ISSUE THREAD

**Issue by madhavi-peddireddy** [UTSAVS26/PyVerse#706]
Project Description:

This project implements a Retrieval-Augmented Generation (RAG) system that allows users to interactively query PDF documents and receive intelligent, context-aware responses using LangChain and Streamlit. By leveraging vector indexing and large language models (LLMs), the system ensures efficient document retrieval and AI-generated responses based on user queries.

![Screenshot (118)](https://github.com/user-attachments/assets/032063c1-2141-4318-9b1e-65784719f590)
![Screenshot (120)](https://github.com/user-attachments/assets/5c44125e-e9f5-4d6a-82b7-05f1ed5a8fa5)
![Screenshot (121)](https://github.com/user-attachments/assets/9003e74b-a639-4b13-883b-655d96e6d3a8)

@UTSAVS26 

I want to work on this issue. Please assign to me

**Comment by UTSAVS26** [comment]
@madhavi-peddireddy your contribution participation role? GSSOC Hacktoberfest ow wob

**Comment by madhavi-peddireddy** [comment]
GSSOC Hacktoberfest

**Comment by madhavi-peddireddy** [comment]
I'm unable to clone this repository.
