### ISSUE TITLE
[Code Addition Request]:  adding 2048 game project to game development

### ISSUE THREAD

**Issue by Riyachauhan11** [UTSAVS26/PyVerse#707]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A (first issue)

### Project Description

The 2048 game is a single-player sliding puzzle where the objective is to combine numbered tiles on a 4x4 grid to create a tile with the number 2048. Players move tiles up, down, left, or right, and when two tiles with the same number collide, they merge into one with their values summed. The game ends when no more moves are possible, either by winning with a 2048 tile or losing when the grid is full and no merges are available. 
Using the tkinter module of ptyhon the UI of game has been designed and put together. 

### Full Name

Riya Chauhan

### Participant Role

Contributor

**Comment by UTSAVS26** [comment]
@Riyachauhan11 have our checked that this game is not already been in the repo and no issues and pr are there?

**Comment by Riyachauhan11** [comment]
oh my bad i didnt check the PRs its there in reviews, ill close this issue and keep in mind checking both issues and PRs section next time. Thank you for the guidance
