### ISSUE TITLE
[Code Addition Request]: CHANAKYA_NITI  Full Stack Web Application

### ISSUE THREAD

**Issue by skanarul8002** [UTSAVS26/PyVerse#708]
### Have you completed your first issue?

- [ ] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

CHANAKYA_NITI is a web application designed to provide an engaging platform for exploring and learning about the teachings of Chanakya, an ancient Indian philosopher, economist, and strategist. The frontend of this application will offer a seamless and interactive user experience. It will connect users with multimedia content, including audio files, books, and videos, and feature an AI-powered personalized recommendation system. The goal is to make Chanakya's timeless wisdom accessible to a modern audience, with features like user authentication, secure backend integration, language translation, and easy API access for users who want to create their own Chanakya-Niti websites.

This is a feature-rich web application that blends tradition with technology, offering an exceptional user experience.

### Full Name

Sk Anarul

### Participant Role

GSSOC-EXT

**Comment by UTSAVS26** [comment]
@skanarul8002 what tech stack you are planning to use?

**Comment by skanarul8002** [comment]
@UTSAVS26 , i will use MERN Stack + different style library.

**Comment by UTSAVS26** [comment]
@skanarul8002 give me tech stack you are planning to use

**Comment by skanarul8002** [comment]
Yeah sure @UTSAVS26, Technologies Used:
**Frontend**:
1. React.js: A JavaScript library for building user interfaces.
2. Redux: State management for handling complex state across the application.
3. Axios: Promise-based HTTP client for making API requests.
4. Material-UI: React components for faster and easier web development.
5. React Router: Declarative routing for React applications.
6. Vite: A build tool that provides a faster and leaner development experience for modern web projects.

**Backend**:
1. Node.js: Server-side JavaScript runtime.
2. Express.js: Web application framework for Node.js.
3. MongoDB: NoSQL database for storing application data.
4. JWT: JSON Web Tokens for secure user authentication.
5. TensorFlow: AI model integration for personalized recommendations and language translation.

**Some important unique Features:**
1. Audio Sound implement
2. Video player
3. Dark/ light toggle
4. Hindi language is used in some part of  website.
5. Entire Web page is responsive
6. And all related functionality, design of Website

Thank you for interaction with me

**Comment by UTSAVS26** [comment]
@skanarul8002 if you confirm that you will use python then only I can allow the project.

**Comment by skanarul8002** [comment]
@UTSAVS26 , I will use the MERN stack (MongoDB, Express, React, Node.js) for web development, and additionally, I will implement machine learning-related technologies to develop a chatbot feature.

I'm sure this is the unique project. So please consider it then i will start my work.

**Comment by UTSAVS26** [comment]
@skanarul8002 based on the work done I will add the level.

**Comment by skanarul8002** [comment]
ok @UTSAVS26
