### ISSUE TITLE
[Code Addition Request]: adding 2d platformer game project to game development

### ISSUE THREAD

**Issue by Riyachauhan11** [UTSAVS26/PyVerse#711]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A (first issue)

### Project Description

This 2D platformer game is a still-screen, tile-based adventure where players navigate each level to reach an exit door. The goal is to avoid hazards like lava pits and enemy sprites, as both cause instant death. Levels are designed with platforms to jump on, obstacles to avoid. As players progress, the difficulty increases with more challenging layouts and enemies.

### Full Name

Riya Chauhan

### Participant Role

Contributor

**Comment by UTSAVS26** [comment]
@Riyachauhan11 you are GSSOC contributor?

**Comment by Riyachauhan11** [comment]
Yes I'm a GSSOC contributor
