### ISSUE TITLE
🧑‍💻: Building a Very beautiful website for Pyverse 

### ISSUE THREAD

**Issue by Ashish-Patnaik** [UTSAVS26/PyVerse#717]
### Title

I will make a better and attractive website for Pyverse which visually looks attractive and more appealing to the users

### Enhancement Aim

A more beautiful and attractive UI for the Pyverse

### Changes

Making of whole website 

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Ashish Patnaik

### Participant Role

GSSOC

**Comment by UTSAVS26** [comment]
@Ashish-Patnaik give me your tech stack you are planning to use.

**Comment by UTSAVS26** [comment]
And any design you have in mind for the UI of the website.

**Comment by Ashish-Patnaik** [comment]
A beautiful animated design that relates with Pyverse actually I don't have screenshots but it's gonna be good ,this is my previous works you can consider if you like than its good if you don't like than you close the PR 
![c](https://github.com/user-attachments/assets/7e104457-3215-49ef-855f-d1f21fc6e488)

**Comment by UTSAVS26** [comment]
Based on the work done i will add the level label.
