### ISSUE TITLE
🧑‍💻: To improve the turtle code

### ISSUE THREAD

**Issue by Chin-may02** [UTSAVS26/PyVerse#73]
### To improve the turtle code
:red_circle: **Title** : Turtle (beginner projects)
:red_circle: **Enhancement Aim** : To make the code simple and easier and enhance it by adding new features
:red_circle: **Changes** : 
1. User specific angle for the turtle to turn
2. If color not specified using default color 

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name: Vuppu Chinmay
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
 Contributor at GSSOC-Extd 2024 and Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by UTSAVS26** [comment]
@Chin-may02 you had only raised a PR on your cloned repo itself and merged it, it is not the PR for the main repo.

**Comment by Chin-may02** [comment]
I shall redo it again
Sorry for the mishap
