### ISSUE TITLE
[Code Addition Request]: Automate Workflows through Web Scraping

### ISSUE THREAD

**Issue by sanchitc05** [UTSAVS26/PyVerse#736]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UppuluriKalyani/ML-Nexus/pull/324

### Project Description

**Description:**  
I propose developing a web scraping tool to automate workflows within PyVerse. This tool will extract data (e.g., prices, news, or stock data) from static and dynamic websites, store it for analysis, and run periodically using schedulers like cron or Task Scheduler.

---

### **Tech Stack:**  
- **Python Libraries**: `requests`, `BeautifulSoup`, `Selenium`  
- **Scheduling**: `cron` (Linux) / Task Scheduler (Windows)  
- **Error Handling and Logs**: `logging` module  

### **Approach:**  
1. Identify websites to scrape based on user needs (e.g., financial or product data).  
2. Build modules for scraping both static and dynamic pages.  
3. Implement automated scheduling with logging for status tracking.  
4. Create detailed documentation and examples to guide users.

---

### **How This Helps Users:**  
- Automates repetitive data extraction tasks.  
- Saves time and ensures users always have the latest data for analysis.  
- Encourages contributions from beginners and advanced users alike through modular code and documentation.

---

Please assign this issue to me so I can begin implementation.

### Full Name

Sanchit Chauhan

### Participant Role

GSSOC, HACKTOBERFEST

**Comment by sanchitc05** [comment]
Hi @UTSAVS26 , 

Thank you for assigning the issue! I’d like to kindly request an update to a level 2 label. The project involves web scraping, which requires handling both static and dynamic content using `requests`, `BeautifulSoup`, and `Selenium`. Additionally, I'll implement error handling and logging to ensure robustness. Given these complexities, I believe a level 2 label would be more appropriate. 

Thank you for your understanding!

**Comment by UTSAVS26** [comment]
Based on work done i will change the level.

**Comment by sanchitc05** [comment]
Hi again @UTSAVS26 I am done with the work on this issue and pulled a request for the same. Please check it whenever you feel comfortable and let me know if you face any doubts regarding anything in the PR feel free to ask me.


Also can you please go through it well and based on my work, I would like to request you to please give me at least level 2 for the work. 

Regards, 
Sanchit Chauhan
