### ISSUE TITLE
[Code Addition Request]: Automate Workflows with File Management Tools

### ISSUE THREAD

**Issue by sanchitc05** [UTSAVS26/PyVerse#737]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UppuluriKalyani/ML-Nexus/pull/324

### Project Description

**Description:**  
I propose creating a **file automation tool** for PyVerse to streamline tasks like moving, renaming, organizing, or backing up files. The goal is to automate routine file operations and reduce manual effort. This tool will improve productivity by organizing files efficiently.  

---

### **Tech Stack:**  
- **Python Libraries:** `os`, `shutil`, `glob`  
- **Scheduling:** `cron` (Linux) / Task Scheduler (Windows)  
- **Error Handling:** `logging`  

---

### **Approach:**  
1. Write scripts to identify and process files based on extensions, dates, or patterns.  
2. Automate file transfers (e.g., backups, folder reorganization).  
3. Provide logs to monitor automation and handle errors gracefully.  

---

### **How This Helps Users:**  
- Automates mundane file tasks to save time.  
- Ensures files remain organized and up-to-date without manual effort.  
- Empower beginners by demonstrating how to automate workflows with Python.  

---

Please assign this issue to me.

### Full Name

Sanchit Chauhan

### Participant Role

GSSOC, HACKTOBERFEST

**Comment by sanchitc05** [comment]
Hi @UTSAVS26 , kindly add the required labels so that I can start working on the issue.

**Comment by UTSAVS26** [comment]
i am closing this one, you can raise 1 issue at a time
