### ISSUE TITLE
Wikipedia Article Scraper

### ISSUE THREAD

**Issue by Aditijainnn** [UTSAVS26/PyVerse#748]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

#555

### Project Description

A python web scraper that retrieves  frequent words with their percentages in an English Wikipedia article and it also stores the top 20 most frequent words in a CSV file.

### Full Name

Aditi

### Participant Role

gssoc ext

**Comment by UTSAVS26** [comment]
@Aditijainnn raise 1 issue at a time.
