### ISSUE TITLE
🧑‍💻: Add challenege on each python dependent project tools

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [UTSAVS26/PyVerse#756]
### Title

Add challenege on each python dependent project tools

### Enhancement Aim

Add challenege on each python dependent project tools

### Changes

Add challenege on each python dependent project tools

### Screenshots 📷

Add challenege on each python dependent project tools

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Bhuvaneswari kapuluru

### Participant Role

gssoc extd

**Comment by UTSAVS26** [comment]
@KapuluruBhuvaneswariVspdbct raise 1 issue at a time.
