### ISSUE TITLE
[Code Addition Request]: Add a simple Web Application Firewall tool

### ISSUE THREAD

**Issue by djv554** [UTSAVS26/PyVerse#758]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/413

### Project Description

Protect web applications by filtering and monitoring HTTP traffic between a web application and the internet, helping to block phishing and other attacks.

### Full Name

Deanne Vaz

### Participant Role

Contributor at GSSoC-extd and Hacktoberfest

**Comment by UTSAVS26** [comment]
@djv554 what tech stack you are planning to use?

**Comment by djv554** [comment]
@UTSAVS26 I'm planning to use the following tech stack:

Language: Python
Framework: Flask
Libraries:
- `re` (for regular expressions)
- `jsonify` (for JSON response formatting)

Security: Input validation via regular expressions for detecting SQL Injection and XSS.
API Design: Simple RESTful endpoint (POST /submit) for user input processing.
