### ISSUE TITLE
🧑‍💻: Enhancement of Task Manager Application: Migration to Streamlit (Advanced_Projects/GUI Based TaskManager)

### ISSUE THREAD

**Issue by shreyasparaj** [UTSAVS26/PyVerse#759]
### Title

Enhancement of Task Manager Application: Migration to Streamlit (Advanced_Projects/GUI Based TaskManager)

### Enhancement Aim

The aim of this enhancement is to migrate the existing Tkinter-based Task Manager application to a more interactive and user-friendly Streamlit web application. This upgrade will provide a modern interface, improve usability, and facilitate task management through a web browser.

### Changes

1. User Interface Transition: Transition from Tkinter to Streamlit for a web-based interface.

2. Task Management Features:

- Maintain functionality for adding, updating, deleting, and completing tasks.
- Include sorting functionality for tasks based on priority and deadline.

3. Input Handling: Implement Streamlit widgets for user input:

- Text input for task description.
- Number input for task priority with defined range (1 to 10).
- Date input for task deadlines, defaulting to today’s date.

4. Dynamic Display: Display the list of tasks dynamically with options to update or delete tasks.

5. Success Feedback: Provide user feedback (success/warning messages) upon task management actions.

### Screenshots 📷

N/A

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

SHREYAS SHRENIK PARAJ PATIL

### Participant Role

GSSOC CONTRIBUTOR

**Comment by shreyasparaj** [comment]
@UTSAVS26 Please assign this issue to me. I am ready to transfer GUI of this task manager app to streamlit.

**Comment by UTSAVS26** [comment]
@shreyasparaj raise 1 issue at a time.
