### ISSUE TITLE
Exploratory Data Analysis of Death Rates

### ISSUE THREAD

**Issue by sharayuanuse** [UTSAVS26/PyVerse#769]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/684#event-14763858737

### Project Description

The main goal of the "Death Rate Analysis" project is to assess mortality statistics across various countries based on different causes of death. The purpose is to aid in improving health policies by analyzing gender-wise death rates and understanding their relationship with factors such as the Human Development Index (HDI) and Gross Domestic Product (GDP).

### Full Name

Sharayu Anuse

### Participant Role

GSSOC-Ext, Hacktoberfest

**Comment by sharayuanuse** [comment]
@UTSAVS26 I need help for the following issue. 
![image](https://github.com/user-attachments/assets/5ecb140b-ae84-40b8-8db9-388f8870d51e)

**Comment by UTSAVS26** [comment]
@sharayuanuse i will correct the issue by today itself, you can try cloning in evening.
