### ISSUE TITLE
Add Rock-Paper-Scissor game in beginners project

### ISSUE THREAD

**Issue by ishicodz** [UTSAVS26/PyVerse#775]
This project is a simple **Rock, Paper, Scissors** game built in Python. It's a fun, interactive game where the user plays against the computer, and the winner is determined based on the classic game rules. This is a beginner-friendly project that showcases basic Python concepts like input handling, conditionals, loops, and random number generation.

<h2>Guidelines</h2>

- [x] I have read the guidelines  
- [ ] I have the link to my latest merged PR

<h2>Full Name</h2>
Ishita Gupta

<h2>Participant Role</h2>
GSSOC'24 | Contributor

&nbsp;

&nbsp;

@UTSAVS26 please assign this issue to me under the `gssoc-ext`, `hacktoberfest-accepted`, and `level` label.

**Comment by UTSAVS26** [comment]
@ishicodz this project has already been added. Will you suggest some new things you are planning to work on?
