### ISSUE TITLE
FEATURE :- Auto-label Workflow 

### ISSUE THREAD

**Issue by archanasingh11** [UTSAVS26/PyVerse#776]
**Description:**

I would like to request the addition of an **auto-label workflow** in this repository to automatically label pull requests with **"gssoc-ext"** and **"hacktoberfest-accepted"** during relevant events such as GSSoC (GirlScript Summer of Code) and Hacktoberfest.

### **Key Features:**
1. **Auto-label on PR Creation:**
   - Automatically apply the **"gssoc-ext"** label for any pull requests submitted as part of GSSoC.
   - Automatically apply the **"hacktoberfest-accepted"** label for pull requests during the Hacktoberfest period, or when contributors indicate Hacktoberfest participation.
   
2. **Workflow Automation:**
   - Use GitHub Actions to create a workflow that triggers upon pull request creation, checking the event or time period, and assigning the appropriate label automatically.
   
3. **Custom Conditions:** 
   - Allow maintainers to manually override the labels if necessary.
   - Include a check to ensure only valid PRs contributing to the project are labeled with **"hacktoberfest-accepted"**, following Hacktoberfest rules.

### **Benefits:**
- **Efficiency:** Automating this process will save time for maintainers by reducing manual labeling.
- **Transparency:** Ensures that contributors clearly know when their pull request has been accepted for relevant events.
- **Compliance:** Helps in staying aligned with the official rules for Hacktoberfest, where labels like **"hacktoberfest-accepted"** are required to validate contributions.

### **Suggested Implementation:**
- Add a GitHub Actions workflow file in `.github/workflows` that triggers on pull request events and applies the labels based on specific conditions.

Please @UTSAVS26 assign me this issue with labels"gssoc-ext", "hacktoberfest-accepted" and "level3"

**Comment by UTSAVS26** [comment]
@archanasingh11 based on how workflow works i will update the level
