### ISSUE TITLE
[Code Addition Request]: Add interactive Hangman game in beginners project

### ISSUE THREAD

**Issue by ishicodz** [UTSAVS26/PyVerse#777]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

This project is a simple and interactive Hangman game implemented in Python. The game allows two players to engage in a fun guessing challenge, where one player chooses a secret word, and the other player must guess it before running out of lives. The game provides a visual representation of the hangman, offering feedback on each guess, and keeps track of remaining lifelines. It’s a beginner-friendly project that introduces core Python concepts like loops, conditionals, and user input.

### Full Name

Ishita Gupta

### Participant Role

GSSOC Contributor

**Comment by ruhi47** [comment]
Hey @ishicodz ,

I've assigned this issue to you—thanks for taking it on! 😊 Just a reminder to check out the contribution guidelines before you dive in. If you have any questions or run into any roadblocks, don’t hesitate to reach out. Looking forward to seeing your work—happy coding!

Cheers!

**Comment by UTSAVS26** [comment]
@ishicodz this project has already been done, tell me what new you are going to incorporate? After it I will add the labels again.
