### ISSUE TITLE
Adding Random Quote Generator in Beginner_Projects

### ISSUE THREAD

**Issue by siri-chandana-macha** [UTSAVS26/PyVerse#790]
- I propose adding a feature that allows users to copy the displayed quote to their clipboard. 
- This enhancement would improve user experience by enabling easy sharing of quotes. 
- Additionally, implementing a favorites list for users to save their preferred quotes would add more functionality

@UTSAVS26 please kindly assign this issue under gssoc-extd , hacktoberfest-accepted and level

**Comment by UTSAVS26** [comment]
@siri-chandana-macha use dedicated issue templates for the same. I am closing this one.
