### ISSUE TITLE
[Code Addition Request]: need to improve some features in tic tac toe game 

### ISSUE THREAD

**Issue by gayathribotlagunta** [UTSAVS26/PyVerse#802]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

need to add some more features in this tic tac toe game . we can implement it by using python .

### Full Name

gayathribotlagunta

### Participant Role

GSSOC
![Uploading gayathri_botlagunta_Badge_Contributor_GSSoC2024-Extd.png…]()

**Comment by UTSAVS26** [comment]
What changes are you planning to integrate?

**Comment by KaroK365** [comment]
I would like to contribute to it

**Comment by UTSAVS26** [comment]
> I would like to contribute to it

What are you planning to do?

**Comment by KaroK365** [comment]
Things I am thinking about changing:-

1. Add Green Highlight color to winning combination.
2. Add Players to enter there name from settings.
3. Add winsound library.
4. Will try to retain the scores.

**Comment by KaroK365** [comment]
Also I am a bit new and would like to ask you one thing is it possible for me to fork only this project and not the whole github repo which contains all project and do my work??

**Comment by KaroK365** [comment]
should i start working on it??
Waiting for your response 😊

**Comment by UTSAVS26** [comment]
> should i start working on it??
> Waiting for your response 😊

You can.

**Comment by KaroK365** [comment]
I have created a PR 😊
