### ISSUE TITLE
🧑‍💻: Enhance Binary search tree

### ISSUE THREAD

**Issue by yashksaini-coder** [UTSAVS26/PyVerse#817]
### Title

Improve the main BST DSA approach 

### Enhancement Aim

My main objective is to implement much better & more good code with better understanding. With this also add few new functions that can be added for BST

### Changes

Add new binary search tree visualizer from lists

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

https://github.com/UTSAVS26/PyVerse/pull/808

### Participant Role

GSSoC-Ext

**Comment by UTSAVS26** [comment]
@yashksaini-coder bro raise 1 issue at a time. I am closing this one.
