### ISSUE TITLE
Jump Search -Searching algorithm adding.

### ISSUE THREAD

**Issue by PradeepFSTdhane123** [UTSAVS26/PyVerse#819]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/818

### Project Description

Like Binary Search, Jump Search is a searching algorithm for sorted arrays. The basic idea is to check fewer elements (than [linear search](https://www.geeksforgeeks.org/analysis-of-algorithms-set-2-asymptotic-analysis/)) by jumping ahead by fixed steps or skipping some elements in place of searching all elements.

### Full Name

Pradeep Laxman Dhane.

### Participant Role

GSSOC-ext, hactoberfest.

**Comment by PradeepFSTdhane123** [comment]
@UTSAVS26 "I would love the opportunity to contribute and work on this project.
Could you please assign the issue to me? I'm eager to dive in and make a meaningful impact. Thank you for considering my request!"

**Comment by UTSAVS26** [comment]
@PradeepFSTdhane123 wait until me or mentors assign you the issue . I am closing the PR alongwith this issue.
