### ISSUE TITLE
Deep Learning Model - James-Web-Telescope

### ISSUE THREAD

**Issue by Varunshiyam** [UTSAVS26/PyVerse#825]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

PR no : https://github.com/UTSAVS26/PyVerse/pull/697 which Solved the Issue https://github.com/UTSAVS26/PyVerse/issues/674
PR no : https://github.com/UTSAVS26/PyVerse/pull/662 which Solved the Issue https://github.com/UTSAVS26/PyVerse/issues/617

### Project Description

This is a Deep learning Project which Recognize the Images from Jame-web-Telescope.

### Full Name

Varunshiyam 

### Participant Role

GSSOC, hacktoberfest

**Comment by UTSAVS26** [comment]
@Varunshiyam raise 1 issue at a time
