### ISSUE TITLE
Adding linkedlist easy level problems

### ISSUE THREAD

**Issue by amiya-cyber** [UTSAVS26/PyVerse#842]
adding linkedlist easy level problems 

A **LinkedList** is a linear data structure in which elements are stored in nodes, and each node points to the next node, forming a chain. Imagine a train where each car is connected to the next car, but you can only move forward through the train. Each car contains passengers (data) and has a coupling (pointer) that connects it to the next car.

**Comment by UTSAVS26** [comment]
@amiya-cyber please use a proper issue template.
