### ISSUE TITLE
Add new beginner level project

### ISSUE THREAD

**Issue by amiya-cyber** [UTSAVS26/PyVerse#844]
The objective of this game is to click on moving circles as they appear on the screen to score points. The game will have a timer, and the player needs to score as many points as possible before the timer runs out.

**Tech Stack**

1. html
2. css 
3. javascript

![2024-10-25 (15)](https://github.com/user-attachments/assets/b6c393be-32ed-4b77-b54a-4efae77d8c6d)

**Comment by megha-66** [comment]
@amiya-cyber Please assign me this issue under hacktoberfest and gssoc-ext please please

**Comment by UTSAVS26** [comment]
Web development related projects that are related to python are only accepted.
