### ISSUE TITLE
📃: Dog Breeds Classification

### ISSUE THREAD

**Issue by IkkiOcean** [UTSAVS26/PyVerse#85]
:red_circle: **Title** : Dog Breeds Classification
:red_circle: **Aim** : The goal of this project is to develop a machine learning model that accurately classifies dog breeds based on their images. Given a dataset of labeled dog images, the task is to predict the correct breed for each image.
:red_circle: **Brief Explanation** :
The primary objective of this project is to accurately classify dog breeds from images using advanced deep learning techniques. By leveraging state-of-the-art convolutional neural network (CNN) architectures, including ResNet50V2, MobileNet, and VGG19, I aim to develop a model capable of predicting the correct breed label for each input image.

Dataset: https://www.kaggle.com/datasets/gpiosenka/70-dog-breedsimage-data-set

### Screenshots 📷
NA

***********************************************************************

- Full name : Vivek Prakash
- What is your participant role?
  GSSOC-extd and hacktoberfest

***********************************************************************

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by UTSAVS26** [comment]
> Can you please assign it to me? I want to work on it.

Sorry but it is already assigned, you can raise another issue.
