### ISSUE TITLE
🧑‍💻: Add cursor aniiamtion effect

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [UTSAVS26/PyVerse#866]
### Title

Add cursor aniiamtion effect

### Enhancement Aim

Add cursor aniiamtion effect

### Changes

Add cursor aniiamtion effect

### Screenshots 📷

https://github.com/user-attachments/assets/50c9f72b-2cb5-460d-a40b-84483d8d68f9

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Bhuvaneswari kapuluru

### Participant Role

Gssoc extd

**Comment by UTSAVS26** [comment]
@KapuluruBhuvaneswariVspdbct there is no coded website present for this project so this issue will not be able to work.
