### ISSUE TITLE
📃: Addition of code for beginners to better understand python 

### ISSUE THREAD

**Issue by Chin-may02** [UTSAVS26/PyVerse#87]
:red_circle: **Title** : Addition of to-do list 
:red_circle: **Aim** : To help the beginners understand the working of python
:red_circle: **Brief Explanation** :  Would like to add a simple code of to-do list to for understanding basics 

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vuppu Chinmay
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
Contributor at GSSOC-Extd 2024 and Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by KartikSaxena19** [comment]
you can assign this task to me

**Comment by UTSAVS26** [comment]
@KartikSaxena19 please raise another issue.
