### ISSUE TITLE
🧑‍💻: Wanted To Update The UI

### ISSUE THREAD

**Issue by milansamuel609** [UTSAVS26/PyVerse#884]
### Title

Improving Maximum Easiness While Using

### Enhancement Aim

Wanted to help the users to easily navigate through the website.

### Changes

1. Wanted to add a search bar in the nav-bar section for easy search of the projects instead of manually searching it.
2. Also wanted to add a contact us page in the footer section. Will provide the LinkedIn profile and also the email given in your profile.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/3f3647a5-b3fa-4be1-8b0c-a75eafc2480e)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

MILAN P SAMUEL

### Participant Role

GSSOC Extend '24

**Comment by UTSAVS26** [comment]
@milansamuel609 there is no coded website for this project, the website has been created using Google Sites.

**Comment by milansamuel609** [comment]
> @milansamuel609 there is no coded website for this project, the website has been created using Google Sites.

Ok 👍
