### ISSUE TITLE
📃: Morse Code with UI

### ISSUE THREAD

**Issue by aviralgarg05** [UTSAVS26/PyVerse#9]
:red_circle: **Title** : Morse Code with GUI
:red_circle: **Aim** : Basic Project for Morse Code conversion
:red_circle: **Brief Explanation** : It contains two functions:
English to Morse Code conversion.
Morse Code to English conversion.
Includes GUI for better user experience.

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aviral Garg
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC '24 Extended

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Brahamanbtp** [comment]
@aviralgarg05 bro can you assign this to me

**Comment by UTSAVS26** [comment]
> @aviralgarg05 bro can you assign this to me

Hello bro, I am the project admin and he is Contributor like you too. 🥲

If you want to contribute in this, then tell me what all you gonna do in it and also add `your participant role (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)`

**Comment by aviralgarg05** [comment]
@UTSAVS26  Can you assign me my issue.
