### ISSUE TITLE
[Code Addition Request]: a website for quick notes taking ( beginner level project)

### ISSUE THREAD

**Issue by amrutha-m206** [UTSAVS26/PyVerse#905]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/Shreyaa173/Code-Book/issues/219

### Project Description

Building a Django notes taking website that allows users to create, view, and delete notes. Uses Django's SQLite database to store notes

### Full Name

Amrutha M

### Participant Role

GSSOC-ext and hacktoberfest

**Comment by amrutha-m206** [comment]
can i also know which level this project belongs to

**Comment by UTSAVS26** [comment]
> can i also know which level this project belongs to

Level 1
