### ISSUE TITLE
🧑‍💻: Adding multi language support system

### ISSUE THREAD

**Issue by amanver45** [UTSAVS26/PyVerse#915]
### Title

I want to add multi language support system to the website which can help us understand in their native language.

### Enhancement Aim

ss

### Changes

s

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

aman verma

### Participant Role

gssoc ext

**Comment by UTSAVS26** [comment]
@amanver45 you need to add all the things that are asked.
