### ISSUE TITLE
🧑‍💻: Adding cursor following animation

### ISSUE THREAD

**Issue by amanver45** [UTSAVS26/PyVerse#917]
### Title

I would like to add a cursor following animation and make it align with the website styling
Kindly assign this to me

### Enhancement Aim

sss

### Changes

s

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Aman Verma

### Participant Role

gssoc ext

**Comment by UTSAVS26** [comment]
@amanver45 don't ass `sss` and so it is not recommended.
