### ISSUE TITLE
[Code Addition Request]: Add a new project

### ISSUE THREAD

**Issue by Dharun235** [UTSAVS26/PyVerse#919]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/900

### Project Description

 Semi-Supervised Image Classification

The main idea is to use a consistency regularization approach to leverage the unlabeled data for training. The process involves:
1. Training a neural network on a small labeled dataset.
2. Adding consistency regularization to utilize the large unlabeled dataset by enforcing that the model's predictions for augmented versions of the same image should be similar.

 Use the CIFAR-10 dataset, which consists of 10 different classes of images. Split the dataset into labeled and unlabeled subsets. For example, use only 10% of the dataset as labeled and the remaining 90% as unlabeled. The model will be trained to make similar predictions for different augmented versions of the same image (e.g., using random cropping, flipping, etc.).

### Full Name

Dharun Kumar

### Participant Role

Contributor in GSSOC'EXTD and Hacktoberfest

**Comment by UTSAVS26** [comment]
@Dharun235 raise 1 issue at a time.

**Comment by Dharun235** [comment]
@UTSAVS26 Okay. 
Thanks.
