### ISSUE TITLE
[Code Addition Request]: Longest Increasing Subsequence | Dynamic Programming

### ISSUE THREAD

**Issue by SKG24** [UTSAVS26/PyVerse#933]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/910
PR #910 

### Project Description

Given an integer array nums, return the length of the longest strictly increasing 
subsequence.

Example 1:
Input: nums = [10,9,2,5,3,7,101,18]
Output: 4
Explanation: The longest increasing subsequence is [2,3,7,101], therefore the length is 4.

### Full Name

Sanat Kumar Gupta

### Participant Role

gssoc-ext, hacktoberfest

**Comment by UTSAVS26** [comment]
@SKG24 raise 1 issue at a time.
