### ISSUE TITLE
Disaster Tweet Classification using NLP and Deep Learning

### ISSUE THREAD

**Issue by Varunshiyam** [UTSAVS26/PyVerse#973]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

PR: #930

### Project Description

This project addresses the challenge of classifying tweets as real disaster events or not. It involves natural language processing (NLP) techniques like TF-IDF vectorization and deep learning models such as Recurrent Neural Networks (RNNs) and Convolutional Neural Networks (CNNs). The project explores different feature engineering methods, including text length, word count, and hashtag count, to improve classification accuracy.  Multiple models are trained and evaluated, with a focus on optimizing performance for real-world disaster response applications.

### Full Name

Varunshiyam

### Participant Role

Gssoc, hacktoberfest

**Comment by UTSAVS26** [comment]
@Varunshiyam same goes for this and you can raise only 1 issue at a time.
