### ISSUE TITLE
[Code Addition Request]: Add a Malware scanner

### ISSUE THREAD

**Issue by djv554** [UTSAVS26/PyVerse#995]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Latest Merged PR Link

https://github.com/UTSAVS26/PyVerse/pull/925

### Project Description

This feature will scan files to detect potentially malicious files by comparing their hash signatures against a predefined list of known malware hashes using the `hashlib` library.

Key features:
- Hash Comparison: Utilizes cryptographic hash functions (e.g., SHA-256) to generate file hashes, allowing for efficient and accurate comparisons against a list of known malware signatures.
- User-Friendly Interface: Offers a simple command-line interface that allows users to easily specify the file or directory to scan.
- Malware Signature Database:  Maintains a list of known malware hashes, enabling the scanner to quickly check against common threats.
- Scan Results: Provides clear feedback on the scan results, indicating whether any files are potentially malicious and listing their hashes for verification
- File System Support: Capable of scanning both individual files and directories, making it versatile for various scanning needs.

### Full Name

Deanne Vaz

### Participant Role

Contributor at GSSoC-extd and Hacktoberfest

**Comment by Tanisha0708** [comment]
@djv554  i would like to Work on this please assign me this issue

**Comment by UTSAVS26** [comment]
> @djv554  i would like to Work on this please assign me this issue

Raise a new issue.
